In [1]:
# Ver versión de Python
!python --version

Python 3.12.13


In [2]:
# Instalar dependencias necesarias
!pip install pymongo

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.8/1.8 MB 19.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 331.1/331.1 kB 7.9 MB/s eta 0:00:00


In [3]:
# Cargar librerias
from pymongo import MongoClient
import numpy as np
import pandas as pd

In [4]:
print("NumPy:", np.__version__)
print("Pandas:", pd.__version__)

NumPy: 2.0.2
Pandas: 2.2.2


## CONFIGURACIÓN

In [5]:
# -----------------------------
# CONFIGURACIÓN
# -----------------------------
MONGO_URI = "mongodb+srv://empleoslaboralai:FElvNQ6lBc254Euc@laboral-cv-service-clus.06txt.mongodb.net/?retryWrites=true&w=majority&appName=laboral-cv-service-cluster"
DB_NAME = "laboral-ai-dev"
SAMPLE_SIZE = 5000   # límite de documentos por colección

## FUNCIONES

In [6]:
# -----------------------------
# FUNCIONES
# -----------------------------

def conectar_mongo(uri, db_name):
    client = MongoClient(uri)
    return client[db_name]

def obtener_colecciones(db):
    return db.list_collection_names()

def muestrear_coleccion(db, coleccion, sample_size=SAMPLE_SIZE):
    cursor = db[coleccion].aggregate([{"$sample": {"size": sample_size}}])
    return pd.DataFrame(list(cursor))

def analizar_dataframe(df, umbral=0.8):
    resultados = []
    for col in df.columns:
        serie = df[col].dropna()

        # Detectar listas/dicts
        if serie.apply(lambda x: isinstance(x, (list, dict))).any():
            resultados.append({
                "campo": col,
                "tipo": "estructura (list/dict)",
                "min": None,
                "max": None,
                "distinctCount": None
            })
            continue

        # Booleanos
        if serie.dtype == "bool":
            resultados.append({
                "campo": col,
                "tipo": "booleano",
                "min": None,
                "max": None,
                "distinctCount": serie.nunique()
            })
            continue

        # Numéricos directos
        if np.issubdtype(serie.dtype, np.number):
            resultados.append({
                "campo": col,
                "tipo": "numérico",
                "min": serie.min(),
                "max": serie.max(),
                "distinctCount": serie.nunique()
            })
            continue

        # Intentar fechas
        serie_dt = pd.to_datetime(serie, errors="coerce")
        if serie_dt.notna().sum() > 0:
            resultados.append({
                "campo": col,
                "tipo": "fecha",
                "min": serie_dt.min(),
                "max": serie_dt.max(),
                "distinctCount": serie_dt.nunique()
            })
            continue

        # Si nada aplica → categórico/texto
        resultados.append({
            "campo": col,
            "tipo": "categórico/texto",
            "min": None,
            "max": None,
            "distinctCount": serie.nunique()
        })
    return pd.DataFrame(resultados)

def analizar_colecciones(db):
    resumen = {}
    for coleccion in obtener_colecciones(db):
        try:
            df = muestrear_coleccion(db, coleccion)
            if not df.empty:
                # Convertir posibles campos de fecha
                for col in df.columns:
                    if df[col].dtype == "object":  # solo si es texto
                        try:
                            df[col] = pd.to_datetime(df[col], errors="coerce")
                        except Exception:
                            pass
                resumen[coleccion] = analizar_dataframe(df)
        except Exception as e:
            print(f"⚠️ Error en {coleccion}: {e}")
    return resumen

## EJECUCIÓN

In [7]:
# -----------------------------
# EJECUCIÓN
# -----------------------------
db = conectar_mongo(MONGO_URI, DB_NAME)
resumen = analizar_colecciones(db)

for coleccion, tabla in resumen.items():
    print(f"\n==============================")
    print(f"\n======== {coleccion} ========")
    print(f"\n==============================")
    print(tabla)

/tmp/ipykernel_623/1498380522.py:86: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df[col] = pd.to_datetime(df[col], errors="coerce")
/tmp/ipykernel_623/1498380522.py:86: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df[col] = pd.to_datetime(df[col], errors="coerce")
/tmp/ipykernel_623/1498380522.py:22: FutureWarning: 'any' with datetime64 dtypes is deprecated and will raise in a future version. Use (obj != pd.Timestamp(0)).any() instead.
  if serie.apply(lambda x: isinstance(x, (list, dict))).any():
/tmp/ipykernel_623/1498380522.py:22: FutureWarning: 'any' with datetime64 dtypes is deprecated and will raise in a future version. Use (obj != pd.Timestamp(0)).any() instead.
  if serie.apply(lambda x: isinstance(x

⚠️ Error en candidate_profiles: PlanExecutor error during aggregation :: caused by :: Sort exceeded memory limit of 33554432 bytes, but did not opt in to external sorting. Aborting operation. Pass allowDiskUse:true to opt in., full error: {'ok': 0.0, 'errmsg': 'PlanExecutor error during aggregation :: caused by :: Sort exceeded memory limit of 33554432 bytes, but did not opt in to external sorting. Aborting operation. Pass allowDiskUse:true to opt in.', 'code': 292, 'codeName': 'QueryExceededMemoryLimitNoDiskUseAllowed', '$clusterTime': {'clusterTime': Timestamp(1786370303, 3), 'signature': {'hash': b'\x1b\xdd\x05\xf5\xbf\xf2\x93\xd3\t\r@\x9c\x1d\xde8H\xfb\xe7\xe7O', 'keyId': 7636780473120718857}}, 'operationTime': Timestamp(1786370303, 3)}


/tmp/ipykernel_623/1498380522.py:86: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df[col] = pd.to_datetime(df[col], errors="coerce")
/tmp/ipykernel_623/1498380522.py:86: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df[col] = pd.to_datetime(df[col], errors="coerce")
/tmp/ipykernel_623/1498380522.py:22: FutureWarning: 'any' with datetime64 dtypes is deprecated and will raise in a future version. Use (obj != pd.Timestamp(0)).any() instead.
  if serie.apply(lambda x: isinstance(x, (list, dict))).any():
/tmp/ipykernel_623/1498380522.py:22: FutureWarning: 'any' with datetime64 dtypes is deprecated and will raise in a future version. Use (obj != pd.Timestamp(0)).any() instead.
  if serie.apply(lambda x: isinstance(x



======== userquizdatas ========

       campo              tipo                         min  \
0        _id  categórico/texto                        None   
1       data  categórico/texto                        None   
2       quiz  categórico/texto                        None   
3       user  categórico/texto                        None   
4  createdAt             fecha  2024-12-25 23:58:09.823000   
5  updatedAt             fecha  2024-12-25 23:58:09.823000   
6        __v          numérico                           0   

                          max  distinctCount  
0                        None              0  
1                        None              0  
2                        None              0  
3                        None              0  
4  2026-08-05 22:03:51.811000            675  
5  2026-08-05 22:03:51.811000            675  
6                           0              1  


======== employabilities ========

                      campo              tipo          

In [8]:
from pymongo import MongoClient

client = MongoClient(MONGO_URI)
db = client["laboral-ai-dev"]

colecciones = db.list_collection_names()

print(f"Total de colecciones: {len(colecciones)}")

for c in sorted(colecciones):
    print(c)

Total de colecciones: 63
admins
aiconversations
aimessages
applicants
applications
auditlogs
campaigns
candidate_profiles
communities
companies
company_catalog
companyreports
courseenrollments
courseleads
courses
creditoperations
credits
cvs
cvs_education
cvs_skills
cvs_workExperience
df_brechas_globales
df_brechas_por_carrera
df_matches
educations
employabilities
errorreports
eventguests
events
firstcvcreditclaims
ikigaianswers
ikigairesults
job_categories
jobalertrequests
jobcompatibilityanalyses
jobcvschemaclasses
jobplatformschemaclasses
jobs
jobs_puestos_requisitos
jobs_requisitos
killerquestioninvitations
killerquestions
knowledgebasearticles
languages
notifications
onboardings
payments
questions
quizresults
quizzes
resettokens
skills
sprints
suggestions
tasks
user_events
usercredits
userformschemas
userikigaidatas
userquizdatas
users
whatsappcampaigns
workexperiences


In [9]:
import pandas as pd

inventario = []

for coleccion in colecciones:

    cantidad = db[coleccion].count_documents({})

    inventario.append({
        "Colección": coleccion,
        "Cantidad registros": cantidad
    })

df = pd.DataFrame(inventario)

df.sort_values("Cantidad registros", ascending=False)

,Colección,Cantidad registros
28,df_matches,271887
5,cvs_skills,16554
47,skills,15712
46,onboardings,13369
24,cvs_workExperience,6334
...,...,...
12,courseleads,0
34,errorreports,0
37,jobcvschemaclasses,0
56,jobplatformschemaclasses,0


## IDENTIFICACIÓN DE COLECCIONES RELACIONADAS CON EMPRESAS

**1. Companies**

In [10]:
company = db["companies"].find_one()

company

{'_id': ObjectId('68fb9d847786ced94f9f0c11'),
 'name': 'Guadalupe Rosario Delgado Pardo',
 'email': 'guadalupe.delgado@est.ikiam.edu.ec',
 'password': '$2b$10$0TzGHwj5LSWks6pBcG6cb.Pm6inHsnucHV0S8IQiYId5l20vujere',
 'isActive': True,
 'createdAt': datetime.datetime(2025, 10, 24, 15, 38, 44, 665000),
 'updatedAt': datetime.datetime(2025, 10, 24, 15, 38, 44, 665000),
 '__v': 0}

In [11]:
company.keys()

dict_keys(['_id', 'name', 'email', 'password', 'isActive', 'createdAt', 'updatedAt', '__v'])

In [12]:
for campo, valor in company.items():
    print(f"{campo}: {type(valor)}")

_id: <class 'bson.objectid.ObjectId'>
name: <class 'str'>
email: <class 'str'>
password: <class 'str'>
isActive: <class 'bool'>
createdAt: <class 'datetime.datetime'>
updatedAt: <class 'datetime.datetime'>
__v: <class 'int'>


In [13]:
import pandas as pd

df_companies = pd.DataFrame(list(db["companies"].find()))

In [14]:
df_companies.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 83 entries, 0 to 82
Data columns (total 34 columns):
 #   Column                   Non-Null Count  Dtype         
---  ------                   --------------  -----         
 0   _id                      83 non-null     object        
 1   name                     83 non-null     object        
 2   email                    83 non-null     object        
 3   password                 83 non-null     object        
 4   isActive                 83 non-null     bool          
 5   createdAt                83 non-null     datetime64[ns]
 6   updatedAt                83 non-null     datetime64[ns]
 7   __v                      83 non-null     int64         
 8   plan                     67 non-null     object        
 9   businessName             18 non-null     object        
 10  country                  18 non-null     object        
 11  description              18 non-null     object        
 12  industry                 43 non-null  

In [15]:
df_companies.isnull().sum()

,0
_id,0
name,0
email,0
password,0
isActive,0
createdAt,0
updatedAt,0
__v,0
plan,16
businessName,65


In [16]:
import pandas as pd

coleccion = "companies"

df = pd.DataFrame(list(db[coleccion].find()))

print(df.shape)
df.head()

(83, 34)


,_id,name,email,password,isActive,createdAt,updatedAt,__v,plan,businessName,...,website,companyType,agreements,benefits,employeeCount,keywords,recognitions,socialMedia,killerQuestions,terms
0,68fb9d847786ced94f9f0c11,Guadalupe Rosario Delgado Pardo,guadalupe.delgado@est.ikiam.edu.ec,$2b$10$0TzGHwj5LSWks6pBcG6cb.Pm6inHsnucHV0S8IQ...,True,2025-10-24 15:38:44.665,2025-10-24 15:38:44.665,0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,6900493bdb711f0cddea3e95,Energy Nort,enernortcompany@hotmail.com,$2b$10$VRWTvNR/1D0IZla2V3qSW.iytq2d.FpJXBbI6dn...,True,2025-10-28 04:40:27.280,2025-10-28 04:40:27.280,0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,69022e2b8d47789fe1bc1065,Guille Suarez Reinoso,guillesr1994@gmail.com,$2b$10$4Pq1.Yum5ffVGyAsEkBz9ObNcYYmfOoytO.yomH...,True,2025-10-29 15:09:31.282,2025-10-29 15:09:31.282,0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,690a3a3e9d8bf55845825a2c,Grimaldo Anthony Ccapacca Chavez,elnuevomundothoni@gmail.com,$2b$10$q0Wv1IN99LDy/bPU9Ag5AOcV4K5ziI2qIWXdaGa...,True,2025-11-04 17:39:10.412,2025-11-04 17:39:10.412,0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,69115c7a9be255790d5950a5,AYRTON KRICKST NIEVES ACOSTA,anieves@utec.edu.pe,$2b$10$WSXkv8JHjoweZyxvc80GTOVXcEJPrZLV3g22p5F...,True,2025-11-10 03:31:06.975,2025-11-10 03:31:06.975,0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN


In [17]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 83 entries, 0 to 82
Data columns (total 34 columns):
 #   Column                   Non-Null Count  Dtype         
---  ------                   --------------  -----         
 0   _id                      83 non-null     object        
 1   name                     83 non-null     object        
 2   email                    83 non-null     object        
 3   password                 83 non-null     object        
 4   isActive                 83 non-null     bool          
 5   createdAt                83 non-null     datetime64[ns]
 6   updatedAt                83 non-null     datetime64[ns]
 7   __v                      83 non-null     int64         
 8   plan                     67 non-null     object        
 9   businessName             18 non-null     object        
 10  country                  18 non-null     object        
 11  description              18 non-null     object        
 12  industry                 43 non-null  

In [18]:
perfil = []

for col in df.columns:

    try:
        unicos = df[col].nunique()
    except TypeError:
        unicos = "Estructura compleja"

    perfil.append({
        "Campo": col,
        "Tipo de dato": str(df[col].dtype),
        "Nulos": df[col].isnull().sum(),
        "% Nulos": round(df[col].isnull().mean()*100,2),
        "Valores únicos": unicos
    })

perfil = pd.DataFrame(perfil)

perfil

,Campo,Tipo de dato,Nulos,% Nulos,Valores únicos
0,_id,object,0,0.00,83
1,name,object,0,0.00,79
2,email,object,0,0.00,83
3,password,object,0,0.00,83
4,isActive,bool,0,0.00,1
5,createdAt,datetime64[ns],0,0.00,83
6,updatedAt,datetime64[ns],0,0.00,83
7,__v,int64,0,0.00,1
8,plan,object,16,19.28,Estructura compleja
9,businessName,object,65,78.31,17


**2. jobs**

In [19]:
coleccion = "jobs"

df_jobs = pd.DataFrame(list(db[coleccion].find()))

print(f"Registros: {df_jobs.shape[0]}")
print(f"Columnas: {df_jobs.shape[1]}")

df_jobs.head()

Registros: 1103
Columnas: 48


,_id,companyId,companyName,title,department,modality,roleDescription,requirements,benefits,contact,...,externalCompanyName,externalLogoUrl,companyLogoUrl,normalizedCompanyName,normalizedExternalUrl,createdById,createdByName,categoryId,noPublishDate,companyCatalogId
0,6912191b74d1880032cff34f,69120eb074d1880032cff302,Laboralin,Practicante Comercial Ecommerce,Equivo de Ventas,presencial,"- Realizar análisis de desempeño por cliente, ...",[{'text': 'Estudiante universitario(a) de últi...,Seguro médico \nPaquete de productos \nMédico ...,nya,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,692797626dc39bf20c52f60f,692790216dc39bf20c52f5f5,FirmEasy Legal,Practicante de Growth & Experimentos de Produc...,Área de Marketing,hibrido,OBJETIVO DEL PUESTO: \nApoyar en la ejecución ...,[{'text': 'Conocimiento básico/intermedio en f...,"- S/. 900 – S/. 1,100 según perfil (Subvención...",-,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,69279ce46dc39bf20c52f61c,692790216dc39bf20c52f5f5,FirmEasy Legal,Practicante de Marketing y Contenido Orgánico ...,Área de Marketing,hibrido,OBJETIVO DEL PUESTO\nGestionar el crecimiento ...,"[{'text': 'Excelente redacción, creatividad y ...","- S/. 850 – S/. 1,000 según perfil (Subvenció...",-,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,69279ddf6dc39bf20c52f62f,692790216dc39bf20c52f5f5,FirmEasy Legal,Asesor Comercial B2B de Software | Part Time,Área de Ventas / Comercial,hibrido,PERFIL\nEstudiantes del último ciclo o egresad...,"[{'text': 'Mayor de edad, DNI vigente. ', 'typ...",- Sueldo fijo S/. 650 (subvención económica me...,-,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,69279f586dc39bf20c52f64b,692790216dc39bf20c52f5f5,FirmEasy Legal,Trafficker Digital | Full Time,Área de Marketing,hibrido,PERFIL\nEgresados de las carreras de Marketing...,[{'text': 'Experiencia o conocimiento en campa...,- Certificación al concluir el programa. \n- S...,-,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN


In [20]:
df_jobs.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1103 entries, 0 to 1102
Data columns (total 48 columns):
 #   Column                 Non-Null Count  Dtype         
---  ------                 --------------  -----         
 0   _id                    1103 non-null   object        
 1   companyId              58 non-null     object        
 2   companyName            58 non-null     object        
 3   title                  1103 non-null   object        
 4   department             1096 non-null   object        
 5   modality               1103 non-null   object        
 6   roleDescription        1081 non-null   object        
 7   requirements           1103 non-null   object        
 8   benefits               1103 non-null   object        
 9   contact                58 non-null     object        
 10  publishUntil           1103 non-null   datetime64[ns]
 11  status                 1103 non-null   object        
 12  createdAt              1103 non-null   datetime64[ns]
 13  upd

In [21]:
perfil = []

for col in df_jobs.columns:

    try:
        unicos = df_jobs[col].nunique()
    except TypeError:
        unicos = "Estructura compleja"

    perfil.append({
        "Campo": col,
        "Tipo de dato": str(df_jobs[col].dtype),
        "Nulos": df_jobs[col].isnull().sum(),
        "% Nulos": round(df_jobs[col].isnull().mean()*100,2),
        "Valores únicos": unicos
    })

perfil_jobs = pd.DataFrame(perfil)

perfil_jobs

,Campo,Tipo de dato,Nulos,% Nulos,Valores únicos
0,_id,object,0,0.00,1103
1,companyId,object,1045,94.74,40
2,companyName,object,1045,94.74,38
3,title,object,0,0.00,943
4,department,object,7,0.63,317
5,modality,object,0,0.00,4
6,roleDescription,object,22,1.99,1065
7,requirements,object,0,0.00,Estructura compleja
8,benefits,object,0,0.00,912
9,contact,object,1045,94.74,19


**3.applications**

In [22]:
coleccion = "applications"

df_applications = pd.DataFrame(list(db[coleccion].find()))

print(f"Registros: {df_applications.shape[0]}")
print(f"Columnas: {df_applications.shape[1]}")

df_applications.head()

Registros: 467
Columnas: 21


,_id,job,applicant,fullName,phone,createdAt,updatedAt,__v,blobName,cvUrl,...,applicationStatus,cv,interview,killerQuestionAnswers,filteringResult,notes,discoverySource,isDeleted,candidateEmail,externalQuestionnaire
0,6917cdf4998d66b34dac075b,6917cd88998d66b34dac0734,6917cdf4998d66b34dac0759,Rafael Alonso Garcia Castillejo,987654321,2025-11-15 00:48:52.932,2025-11-15 00:48:53.118,0.0,6917cdf4998d66b34dac075b/cv-rafael-alonso-garc...,https://laboralpdf.blob.core.windows.net/cvs-a...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,692867743b4884927933f66e,692797626dc39bf20c52f60f,692867743b4884927933f66c,Leandro Ledesma,+5491164095745,2025-11-27 15:00:04.307,2025-11-27 15:00:04.551,0.0,692867743b4884927933f66e/cvlean.pdf,https://laboralpdf.blob.core.windows.net/cvs-a...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,6928ab6e985136edda36ae82,69279ce46dc39bf20c52f61c,6928ab6e985136edda36ae80,Claudia Fasabi de la Puente,923544543,2025-11-27 19:50:06.623,2025-11-27 19:50:06.810,0.0,6928ab6e985136edda36ae82/cv-claudia-fasabi.pdf,https://laboralpdf.blob.core.windows.net/cvs-a...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,692a2b217f1f3ab5036abc0d,69279ddf6dc39bf20c52f62f,692a2b207f1f3ab5036abc0b,Rodrigo Salvador Apaza Díaz,959343341,2025-11-28 23:07:13.054,2025-11-28 23:07:13.460,0.0,692a2b217f1f3ab5036abc0d/cv-rodrigo-apaza-2-.pdf,https://laboralpdf.blob.core.windows.net/cvs-a...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,692a5c537f1f3ab5036abe21,69279ce46dc39bf20c52f61c,692a5c537f1f3ab5036abe1f,Jeniffer Paniora Sulca,930753426,2025-11-29 02:37:07.991,2025-11-29 02:37:08.251,0.0,692a5c537f1f3ab5036abe21/cv-jeniffer-paniora-s...,https://laboralpdf.blob.core.windows.net/cvs-a...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN


In [23]:
df_applications.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 467 entries, 0 to 466
Data columns (total 21 columns):
 #   Column                 Non-Null Count  Dtype         
---  ------                 --------------  -----         
 0   _id                    467 non-null    object        
 1   job                    467 non-null    object        
 2   applicant              467 non-null    object        
 3   fullName               467 non-null    object        
 4   phone                  445 non-null    object        
 5   createdAt              466 non-null    datetime64[ns]
 6   updatedAt              466 non-null    datetime64[ns]
 7   __v                    466 non-null    float64       
 8   blobName               463 non-null    object        
 9   cvUrl                  463 non-null    object        
 10  user                   227 non-null    object        
 11  applicationStatus      315 non-null    object        
 12  cv                     92 non-null     object        
 13  inter

In [24]:
perfil = []

for col in df_applications.columns:

    try:
        unicos = df_applications[col].nunique()
    except TypeError:
        unicos = "Estructura compleja"

    perfil.append({
        "Campo": col,
        "Tipo de dato": str(df_applications[col].dtype),
        "Nulos": df_applications[col].isnull().sum(),
        "% Nulos": round(df_applications[col].isnull().mean()*100,2),
        "Valores únicos": unicos
    })

perfil_applications = pd.DataFrame(perfil)

perfil_applications

,Campo,Tipo de dato,Nulos,% Nulos,Valores únicos
0,_id,object,0,0.00,467
1,job,object,0,0.00,46
2,applicant,object,0,0.00,383
3,fullName,object,0,0.00,379
4,phone,object,22,4.71,359
5,createdAt,datetime64[ns],1,0.21,466
6,updatedAt,datetime64[ns],1,0.21,466
7,__v,float64,1,0.21,1
8,blobName,object,4,0.86,463
9,cvUrl,object,4,0.86,463


**4.payments**

In [25]:
coleccion = "payments"

df_payments = pd.DataFrame(list(db[coleccion].find()))

print(f"Registros: {df_payments.shape[0]}")
print(f"Columnas: {df_payments.shape[1]}")

df_payments.head()

Registros: 19
Columnas: 15


,_id,mercadopagoPaymentId,status,statusDetail,paymentMethodId,paymentMethod,amount,currency,products,userId,metadata,externalReference,createdAt,updatedAt,__v
0,69e1ac61b4be029cfbd0eafb,155151636098,approved,accredited,yape,{'data': {'routing_data': {'merchant_account_i...,9.90,PEN,"[{'id': 'intermediate', 'quantity': '1', 'titl...",67157330d544c8d7a551302d,"{'user_email': 'e.holguin993@gmail.com', 'user...",67157330d544c8d7a551302d:intermediate:a3e6ef70...,2026-04-17 03:43:29.053,2026-04-17 03:43:29.053,0
1,69e7d24e3708aede00e538f9,155059193289,approved,accredited,visa,{'data': {'routing_data': {'merchant_account_i...,15.00,PEN,"[{'id': 'advanced', 'quantity': '1', 'title': ...",69d95dea0031803ca9e048cf,"{'user_email': 'rj.buleje@gmail.com', 'user_id...",69d95dea0031803ca9e048cf:advanced:7ddab2b801db...,2026-04-21 19:38:54.095,2026-04-21 19:38:54.095,0
2,69eb7c96cefd4d145d3edb7c,155470126925,approved,accredited,yape,{'data': {'routing_data': {'merchant_account_i...,3.00,PEN,[],687711a049fccafa69055cb8,"{'course_id': '69eb7a737c491af9f1c411c7', 'pay...",course:687711a049fccafa69055cb8:69eb7a737c491a...,2026-04-24 14:22:14.657,2026-04-24 14:22:14.657,0
3,69ebdffd2ba44812bb85c760,156293046060,approved,accredited,yape,{'data': {'routing_data': {'merchant_account_i...,2.99,PEN,[],687711a049fccafa69055cb8,"{'course_id': '69b3c0c3d5534aa59d91445e', 'pay...",certificate:687711a049fccafa69055cb8:69b3c0c3d...,2026-04-24 21:26:21.713,2026-04-24 21:26:21.713,0
4,69fc42ac4e0dd022fb6ee1c3,157341908571,approved,accredited,yape,{'data': {'routing_data': {'merchant_account_i...,3.00,PEN,[],68769e8f49fccafa6905579b,"{'payment_type': 'EVENT_REGISTRATION', 'user_e...",event:68769e8f49fccafa6905579b:69fc40d3200eaa4...,2026-05-07 07:43:40.087,2026-05-07 07:43:40.087,0


In [26]:
df_payments.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 19 entries, 0 to 18
Data columns (total 15 columns):
 #   Column                Non-Null Count  Dtype         
---  ------                --------------  -----         
 0   _id                   19 non-null     object        
 1   mercadopagoPaymentId  19 non-null     object        
 2   status                19 non-null     object        
 3   statusDetail          19 non-null     object        
 4   paymentMethodId       19 non-null     object        
 5   paymentMethod         19 non-null     object        
 6   amount                19 non-null     float64       
 7   currency              19 non-null     object        
 8   products              19 non-null     object        
 9   userId                19 non-null     object        
 10  metadata              19 non-null     object        
 11  externalReference     19 non-null     object        
 12  createdAt             19 non-null     datetime64[ns]
 13  updatedAt             

In [27]:
perfil = []

for col in df_payments.columns:

    try:
        unicos = df_payments[col].nunique()
    except TypeError:
        unicos = "Estructura compleja"

    perfil.append({
        "Campo": col,
        "Tipo de dato": str(df_payments[col].dtype),
        "Nulos": df_payments[col].isnull().sum(),
        "% Nulos": round(df_payments[col].isnull().mean()*100,2),
        "Valores únicos": unicos
    })

perfil_payments = pd.DataFrame(perfil)

perfil_payments

,Campo,Tipo de dato,Nulos,% Nulos,Valores únicos
0,_id,object,0,0.0,19
1,mercadopagoPaymentId,object,0,0.0,19
2,status,object,0,0.0,1
3,statusDetail,object,0,0.0,1
4,paymentMethodId,object,0,0.0,3
5,paymentMethod,object,0,0.0,Estructura compleja
6,amount,float64,0,0.0,6
7,currency,object,0,0.0,1
8,products,object,0,0.0,Estructura compleja
9,userId,object,0,0.0,16


**5.users**

In [28]:
coleccion = "users"

df_users = pd.DataFrame(list(db[coleccion].find()))

print(f"Registros: {df_users.shape[0]}")
print(f"Columnas: {df_users.shape[1]}")

df_users.head()

Registros: 3244
Columnas: 28


,_id,email,password,firstName,lastName,isActive,createdAt,updatedAt,__v,employmentStatus,...,deletedAt,profilePhoto,profileBanner,disponibilidad,location,modalidad,rubros,linkedin,linkedinProfile,notificationPreferences
0,66ba1b36db5c98b2ee73e53c,huamanveramilagros@gmail.com,$2b$10$N5cnsgshLMOyF140jsHtZeGQ8Q4tobYip..sAmK...,Milagros Gladys,Huaman Vera,True,2024-08-12 14:24:54.979,2026-08-10 00:00:01.894,0,Sin experiencia activa,...,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,66ba1b80db5c98b2ee73e625,juanpiruesta@gmail.com,$2b$10$jXAg4wDBh1YamIG8Xt/eZu3eSsizoUiU7Hb9n4p...,Juan Pedro,Ruesta Barboza,True,2024-08-12 14:26:08.031,2026-08-10 00:00:02.850,0,Sin experiencia activa,...,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,66ba1bb3db5c98b2ee73e6ac,margarita_1199@hotmail.com,$2b$10$U..pxBbOgyJ/9dxzZFB0UexUoGcxKVpTwowji.D...,Olga Margarita,Coaguila Meza,True,2024-08-12 14:26:59.177,2026-08-10 00:00:03.265,0,Sin experiencia activa,...,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,66ba1bf9db5c98b2ee73e7e7,Pierodiaza@hotmail.com,$2b$10$57FjbnchiItYMKx.Iczq.OxQOhSzNZurFQwisJV...,Piero Max,Diaz Aliaga,True,2024-08-12 14:28:09.751,2026-08-10 00:00:04.323,0,Sin experiencia activa,...,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,66ba1c0bdb5c98b2ee73e83a,ashleyiman60@gmail.com,$2b$10$BLYZQkivi51CTCrRKKMXYO7UdmxT1QW1RqSbYDc...,Ashley Ivonne,Iman Mallqui,True,2024-08-12 14:28:27.593,2026-08-10 00:00:04.886,0,Sin experiencia activa,...,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN


In [29]:
df_users.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3244 entries, 0 to 3243
Data columns (total 28 columns):
 #   Column                     Non-Null Count  Dtype         
---  ------                     --------------  -----         
 0   _id                        3244 non-null   object        
 1   email                      3244 non-null   object        
 2   password                   3244 non-null   object        
 3   firstName                  3244 non-null   object        
 4   lastName                   3244 non-null   object        
 5   isActive                   3244 non-null   bool          
 6   createdAt                  3244 non-null   datetime64[ns]
 7   updatedAt                  3244 non-null   datetime64[ns]
 8   __v                        3244 non-null   int64         
 9   employmentStatus           3240 non-null   object        
 10  employmentStatusUpdatedAt  3240 non-null   datetime64[ns]
 11  isOnBoarded                3128 non-null   object        
 12  credit

In [30]:
perfil = []

for col in df_users.columns:

    try:
        unicos = df_users[col].nunique()
    except TypeError:
        unicos = "Estructura compleja"

    perfil.append({
        "Campo": col,
        "Tipo de dato": str(df_users[col].dtype),
        "Nulos": df_users[col].isnull().sum(),
        "% Nulos": round(df_users[col].isnull().mean()*100,2),
        "Valores únicos": unicos
    })

perfil_users = pd.DataFrame(perfil)

perfil_users

,Campo,Tipo de dato,Nulos,% Nulos,Valores únicos
0,_id,object,0,0.00,3244
1,email,object,0,0.00,3244
2,password,object,0,0.00,3244
3,firstName,object,0,0.00,2466
4,lastName,object,0,0.00,2813
5,isActive,bool,0,0.00,2
6,createdAt,datetime64[ns],0,0.00,3244
7,updatedAt,datetime64[ns],0,0.00,3244
8,__v,int64,0,0.00,1
9,employmentStatus,object,4,0.12,3


**6.candidate_profiles**

In [31]:
coleccion = "candidate_profiles"

df_candidate_profiles = pd.DataFrame(list(db[coleccion].find()))

print(f"Registros: {df_candidate_profiles.shape[0]}")
print(f"Columnas: {df_candidate_profiles.shape[1]}")

df_candidate_profiles.head()

Registros: 1454
Columnas: 21


,_id,cvId,__v,createdAt,educationTop,email,embeddingProfile,embeddingVersion,fullName,hasEmail,...,isActive,phone,profession,profileTextNormalized,skillsNormalized,summary,updatedAt,updatedAtEmbedding,updatedAtSource,workExperienceTop
0,69e6d54c623f6d4c123cccc9,66b975f0bf7e18bdfd263821,0,2026-04-21 01:39:22.832,[Bachiller en Arte con mención en Diseño Gráfi...,alexandra.justo@pucp.edu.pe,"[-0.029677277, -0.023720643, 0.01630794, -0.02...",v1,Alexandra Justo,True,...,True,+51 974 317 037,Diseñadora Gráfica,disenadora grafica mi proposito es formar part...,"[burreando, etica, diseno tipografico, english]",Mi propósito es formar parte de un entorno don...,2026-04-21 01:39:22.832,2026-04-21 01:39:22.371,2024-11-03 18:00:03.897,[]
1,69e6d54c623f6d4c123cccca,66b9789d1f38bd5f50205458,0,2026-04-21 01:39:22.833,"[Profesional en Diseño Gráfico, Diplomado en m...",yolima.andrades@gmail.com,"[-0.035110734, -0.019184353, -0.00015313826, -...",v1,Yolima Andrades,True,...,True,987579196,UX-UI Designer,ux-ui designer soy un profesional en diseno gr...,"[fortaleza, orientacion al cliente, desarrollo...",Soy un profesional en Diseño Gráfico especiali...,2026-04-21 01:39:22.833,2026-04-21 01:39:22.373,2024-12-26 21:29:31.365,[]
2,69e6d54c623f6d4c123ccccb,66b983401f38bd5f50205589,0,2026-04-21 01:39:22.834,"[Sistemas de Información, Ciencias de la Compu...",denrodbau@gmail.com,"[-0.020337021, -0.015122742, 0.004407466, -0.0...",v1,Denzel Bautista Rodriguez,True,...,True,937020779,Estudiante de Computación,estudiante de computacion soy estudiante de te...,[],Soy estudiante de tercer año de Ciencias de la...,2026-04-21 01:39:22.834,2026-04-21 01:39:22.373,2024-08-12 03:36:32.609,[]
3,69e6d54c623f6d4c123ccccc,66b9a68a7f17c490ad1953a0,0,2026-04-21 01:39:22.834,[Bachiller en Arte con mención en Diseño Gráfi...,alexandra.justo@pucp.edu.pe,"[-0.02523165, -0.018116036, 0.029194942, -0.02...",v1,Alexandra Justo,True,...,True,+51 974 317 037,Diseñadora Gráfica,disenadora grafica mi proposito es formar part...,[],Mi propósito es formar parte de un entorno don...,2026-04-21 01:39:22.834,2026-04-21 01:39:22.374,2024-08-12 06:07:06.980,[]
4,69e6d54c623f6d4c123ccccd,66b97e3a1f38bd5f50205494,0,2026-04-21 01:39:22.833,[Bachiller en Ingeniería de Software],josy130396@gmail.com,"[-0.021611951, -0.0157621, 0.0037611022, -0.01...",v1,Enrique Pacherres,True,...,True,998911987,Diseñador UX/UI junior,disenador ux/ui junior disenador ux/ui junior ...,"[proactivo, c#, cobol, prudencia, justicia, or...",Diseñador UX/UI junior con conocimientos en di...,2026-04-21 01:39:22.833,2026-04-21 01:39:22.373,2024-08-12 03:15:06.823,[]


In [32]:
df_candidate_profiles.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1454 entries, 0 to 1453
Data columns (total 21 columns):
 #   Column                 Non-Null Count  Dtype         
---  ------                 --------------  -----         
 0   _id                    1454 non-null   object        
 1   cvId                   1454 non-null   object        
 2   __v                    1454 non-null   int64         
 3   createdAt              1454 non-null   datetime64[ns]
 4   educationTop           1454 non-null   object        
 5   email                  1454 non-null   object        
 6   embeddingProfile       1454 non-null   object        
 7   embeddingVersion       1454 non-null   object        
 8   fullName               1454 non-null   object        
 9   hasEmail               1454 non-null   bool          
 10  hasPhone               1454 non-null   bool          
 11  isActive               1454 non-null   bool          
 12  phone                  1454 non-null   object        
 13  pro

In [33]:
perfil = []

for col in df_candidate_profiles.columns:

    try:
        unicos = df_candidate_profiles[col].nunique()
    except TypeError:
        unicos = "Estructura compleja"

    perfil.append({
        "Campo": col,
        "Tipo de dato": str(df_candidate_profiles[col].dtype),
        "Nulos": df_candidate_profiles[col].isnull().sum(),
        "% Nulos": round(df_candidate_profiles[col].isnull().mean()*100,2),
        "Valores únicos": unicos
    })

perfil_candidate_profiles = pd.DataFrame(perfil)

perfil_candidate_profiles

,Campo,Tipo de dato,Nulos,% Nulos,Valores únicos
0,_id,object,0,0.0,1454
1,cvId,object,0,0.0,1454
2,__v,int64,0,0.0,1
3,createdAt,datetime64[ns],0,0.0,119
4,educationTop,object,0,0.0,Estructura compleja
5,email,object,0,0.0,1275
6,embeddingProfile,object,0,0.0,Estructura compleja
7,embeddingVersion,object,0,0.0,1
8,fullName,object,0,0.0,1311
9,hasEmail,bool,0,0.0,1


In [34]:
df_companies.columns.tolist()

['_id',
 'name',
 'email',
 'password',
 'isActive',
 'createdAt',
 'updatedAt',
 '__v',
 'plan',
 'businessName',
 'country',
 'description',
 'industry',
 'phone',
 'representativeName',
 'taxIdType',
 'linkedin',
 'taxIdNumber',
 'logo',
 'notificationPreferences',
 'rpaPermissions',
 'address',
 'representative',
 'verificationStatus',
 'website',
 'companyType',
 'agreements',
 'benefits',
 'employeeCount',
 'keywords',
 'recognitions',
 'socialMedia',
 'killerQuestions',
 'terms']

In [35]:
df_companies.head(1).T

,0
_id,68fb9d847786ced94f9f0c11
name,Guadalupe Rosario Delgado Pardo
email,guadalupe.delgado@est.ikiam.edu.ec
password,$2b$10$0TzGHwj5LSWks6pBcG6cb.Pm6inHsnucHV0S8IQ...
isActive,True
createdAt,2025-10-24 15:38:44.665000
updatedAt,2025-10-24 15:38:44.665000
__v,0
plan,NaN
businessName,NaN


In [36]:
df_jobs[df_jobs["companyName"].notna()].head().T

,0,1,2,3,4
_id,6912191b74d1880032cff34f,692797626dc39bf20c52f60f,69279ce46dc39bf20c52f61c,69279ddf6dc39bf20c52f62f,69279f586dc39bf20c52f64b
companyId,69120eb074d1880032cff302,692790216dc39bf20c52f5f5,692790216dc39bf20c52f5f5,692790216dc39bf20c52f5f5,692790216dc39bf20c52f5f5
companyName,Laboralin,FirmEasy Legal,FirmEasy Legal,FirmEasy Legal,FirmEasy Legal
title,Practicante Comercial Ecommerce,Practicante de Growth & Experimentos de Produc...,Practicante de Marketing y Contenido Orgánico ...,Asesor Comercial B2B de Software | Part Time,Trafficker Digital | Full Time
department,Equivo de Ventas,Área de Marketing,Área de Marketing,Área de Ventas / Comercial,Área de Marketing
modality,presencial,hibrido,hibrido,hibrido,hibrido
roleDescription,"- Realizar análisis de desempeño por cliente, ...",OBJETIVO DEL PUESTO: \nApoyar en la ejecución ...,OBJETIVO DEL PUESTO\nGestionar el crecimiento ...,PERFIL\nEstudiantes del último ciclo o egresad...,PERFIL\nEgresados de las carreras de Marketing...
requirements,[{'text': 'Estudiante universitario(a) de últi...,[{'text': 'Conocimiento básico/intermedio en f...,"[{'text': 'Excelente redacción, creatividad y ...","[{'text': 'Mayor de edad, DNI vigente. ', 'typ...",[{'text': 'Experiencia o conocimiento en campa...
benefits,Seguro médico \nPaquete de productos \nMédico ...,"- S/. 900 – S/. 1,100 según perfil (Subvención...","- S/. 850 – S/. 1,000 según perfil (Subvenció...",- Sueldo fijo S/. 650 (subvención económica me...,- Certificación al concluir el programa. \n- S...
contact,nya,-,-,-,-


In [37]:
df_companies[df_companies["businessName"].notna()].head().T

,8,15,16,19,20
_id,692f56d3aafd375d6d269ff1,6951a182c1495a0c80376290,6957d4ba9c1d6916d378256e,69715032e4f81e18f9196cb2,6976a0827af3401857d4286a
name,Laboral.AI,Laboral,Laboral.ai,Nova Maquinarias,Estate Business
email,info@laboral.ai,johmullisaca@hotmail.com,krickst@gmail.com,max.sanroman@nova.pe,carlvego@gmail.com
password,$2b$10$5A84DlBUgzhQ.XIOpp7JA.ayOkosIbb933NjcxE...,$2b$10$mUIJVwaP4.BiKYfTP9kRX.6xmSWlAtxxZibTX2K...,$2b$10$og56MyALugCqohNPQXP91eWfy8nU43z1C83GZZm...,$2b$10$gxDPvXvSBTobSz5bHZY9Yuw4fCJ7vLMw6aAJPLC...,$2b$10$FEMUoIurjqPnKaDVYb35E.Mdu9gA6NQ5uw48IYX...
isActive,True,True,True,True,True
createdAt,2025-12-02 21:14:59.728000,2025-12-28 21:30:42.176000,2026-01-02 14:22:50.126000,2026-01-21 22:16:18.466000,2026-01-25 23:00:18.921000
updatedAt,2026-01-25 01:35:49.906000,2026-02-24 04:49:14.335000,2026-01-03 03:50:10.309000,2026-01-28 18:56:59.306000,2026-01-28 18:15:17.860000
__v,0,0,0,0,0
plan,"{'type': 'FREE_TRIAL', 'freeTrial': {'startedA...","{'type': 'FREE_TRIAL', 'freeTrial': {'startedA...",NaN,"{'type': 'FREE_TRIAL', 'freeTrial': {'startedA...","{'type': 'FREE_TRIAL', 'freeTrial': {'startedA..."
businessName,Testhack Corp S.A.C.S.,1234,Laboral SAC,Nova Maquinarias,CJ Inversiones EIRL


## EXTRAER Y ALOJAR COLUMNAS NECESARIAS POR COLECCIÓN

Seleccionamos solo las columnas que necesitamos.


*  **Crear el DataFrame de companies**







In [38]:
companies = df_companies[
    [
        "_id",
        "businessName",
        "industry",
        "verificationStatus",
        "country",
        "plan",
        "isActive",
        "createdAt"
    ]
].copy()

In [39]:
companies.head()

,_id,businessName,industry,verificationStatus,country,plan,isActive,createdAt
0,68fb9d847786ced94f9f0c11,NaN,NaN,NaN,NaN,NaN,True,2025-10-24 15:38:44.665
1,6900493bdb711f0cddea3e95,NaN,NaN,NaN,NaN,NaN,True,2025-10-28 04:40:27.280
2,69022e2b8d47789fe1bc1065,NaN,NaN,NaN,NaN,NaN,True,2025-10-29 15:09:31.282
3,690a3a3e9d8bf55845825a2c,NaN,NaN,NaN,NaN,NaN,True,2025-11-04 17:39:10.412
4,69115c7a9be255790d5950a5,NaN,NaN,NaN,NaN,NaN,True,2025-11-10 03:31:06.975



*  **Crear el DataFrame de jobs**







In [40]:
jobs = df_jobs[
    [
        "_id",
        "companyId",
        "title",
        "department",
        "modality",
        "publishUntil",
        "status",
        "createdAt",
        "country",
        "geographicDepartment",
        "jobType",
        "verificationStatus",
        "isExternalOffer",
        "externalCompanyName"
    ]
].copy()

In [41]:
jobs.head()

,_id,companyId,title,department,modality,publishUntil,status,createdAt,country,geographicDepartment,jobType,verificationStatus,isExternalOffer,externalCompanyName
0,6912191b74d1880032cff34f,69120eb074d1880032cff302,Practicante Comercial Ecommerce,Equivo de Ventas,presencial,2025-11-11,CLOSED,2025-11-10 16:55:55.029,NaN,NaN,NaN,NaN,NaN,NaN
1,692797626dc39bf20c52f60f,692790216dc39bf20c52f5f5,Practicante de Growth & Experimentos de Produc...,Área de Marketing,hibrido,2025-12-20,CLOSED,2025-11-27 00:12:18.476,NaN,NaN,NaN,NaN,NaN,NaN
2,69279ce46dc39bf20c52f61c,692790216dc39bf20c52f5f5,Practicante de Marketing y Contenido Orgánico ...,Área de Marketing,hibrido,2025-12-20,CLOSED,2025-11-27 00:35:48.105,NaN,NaN,NaN,NaN,NaN,NaN
3,69279ddf6dc39bf20c52f62f,692790216dc39bf20c52f5f5,Asesor Comercial B2B de Software | Part Time,Área de Ventas / Comercial,hibrido,2025-12-20,CLOSED,2025-11-27 00:39:59.268,NaN,NaN,NaN,NaN,NaN,NaN
4,69279f586dc39bf20c52f64b,692790216dc39bf20c52f5f5,Trafficker Digital | Full Time,Área de Marketing,hibrido,2025-12-20,CLOSED,2025-11-27 00:46:16.849,NaN,NaN,NaN,NaN,NaN,NaN



*  **Crear el DataFrame de applications**







In [42]:
applications = df_applications[
    [
        "_id",
        "job",
        "createdAt",
        "applicationStatus"
    ]
].copy()

In [43]:
applications.head()

,_id,job,createdAt,applicationStatus
0,6917cdf4998d66b34dac075b,6917cd88998d66b34dac0734,2025-11-15 00:48:52.932,NaN
1,692867743b4884927933f66e,692797626dc39bf20c52f60f,2025-11-27 15:00:04.307,NaN
2,6928ab6e985136edda36ae82,69279ce46dc39bf20c52f61c,2025-11-27 19:50:06.623,NaN
3,692a2b217f1f3ab5036abc0d,69279ddf6dc39bf20c52f62f,2025-11-28 23:07:13.054,NaN
4,692a5c537f1f3ab5036abe21,69279ce46dc39bf20c52f61c,2025-11-29 02:37:07.991,NaN


**EXPLORACIÓN BÁSICA ORIENTADO A CALIDAD DE DATOS**




*   **Exploración básica orientada a calidad de datos en companies**

In [44]:
companies.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 83 entries, 0 to 82
Data columns (total 8 columns):
 #   Column              Non-Null Count  Dtype         
---  ------              --------------  -----         
 0   _id                 83 non-null     object        
 1   businessName        18 non-null     object        
 2   industry            43 non-null     object        
 3   verificationStatus  50 non-null     object        
 4   country             18 non-null     object        
 5   plan                67 non-null     object        
 6   isActive            83 non-null     bool          
 7   createdAt           83 non-null     datetime64[ns]
dtypes: bool(1), datetime64[ns](1), object(6)
memory usage: 4.7+ KB


In [45]:
print(f"Registros: {companies.shape[0]}")
print(f"Columnas: {companies.shape[1]}")

Registros: 83
Columnas: 8


In [46]:
companies.isnull().sum()

,0
_id,0
businessName,65
industry,40
verificationStatus,33
country,65
plan,16
isActive,0
createdAt,0


In [47]:
(
    companies.isnull().mean()*100
).round(2).sort_values(ascending=False)

,0
businessName,78.31
country,78.31
industry,48.19
verificationStatus,39.76
plan,19.28
_id,0.00
isActive,0.00
createdAt,0.00


In [48]:
companies["_id"].duplicated().sum()

np.int64(0)

In [49]:
companies["businessName"].duplicated().sum()

np.int64(65)

In [50]:
companies["plan"].dropna().iloc[0]

{'type': 'FREE_TRIAL',
 'freeTrial': {'startedAt': datetime.datetime(2026, 1, 13, 20, 43, 56, 248000),
  'endsAt': datetime.datetime(2026, 4, 13, 20, 43, 56, 248000)}}



*   **Exploración básica orientada a calidad de datos en jobs**

In [51]:
jobs.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1103 entries, 0 to 1102
Data columns (total 14 columns):
 #   Column                Non-Null Count  Dtype         
---  ------                --------------  -----         
 0   _id                   1103 non-null   object        
 1   companyId             58 non-null     object        
 2   title                 1103 non-null   object        
 3   department            1096 non-null   object        
 4   modality              1103 non-null   object        
 5   publishUntil          1103 non-null   datetime64[ns]
 6   status                1103 non-null   object        
 7   createdAt             1103 non-null   datetime64[ns]
 8   country               1024 non-null   object        
 9   geographicDepartment  1072 non-null   object        
 10  jobType               630 non-null    object        
 11  verificationStatus    1072 non-null   object        
 12  isExternalOffer       1050 non-null   object        
 13  externalCompanyNam

In [52]:
print(f"Registros: {jobs.shape[0]}")
print(f"Columnas: {jobs.shape[1]}")

Registros: 1103
Columnas: 14


In [53]:
jobs.isnull().sum()

,0
_id,0
companyId,1045
title,0
department,7
modality,0
publishUntil,0
status,0
createdAt,0
country,79
geographicDepartment,31


In [54]:
(
    jobs.isnull().mean()*100
).round(2).sort_values(ascending=False)

,0
companyId,94.74
jobType,42.88
country,7.16
externalCompanyName,5.26
isExternalOffer,4.81
geographicDepartment,2.81
verificationStatus,2.81
department,0.63
title,0.00
_id,0.00


In [55]:
jobs["_id"].duplicated().sum()

np.int64(0)

In [56]:
jobs.nunique()

,0
_id,1103
companyId,40
title,943
department,317
modality,4
publishUntil,95
status,2
createdAt,1103
country,3
geographicDepartment,17


In [57]:
jobs["title"].duplicated().sum()

np.int64(160)

In [58]:
jobs["modality"].value_counts(dropna=False)

,count
modality,
presencial,953
hibrido,70
remoto,67
híbrido,13


In [59]:
jobs["status"].value_counts(dropna=False)

,count
status,
OPEN,903
CLOSED,200


In [60]:
jobs["jobType"].value_counts(dropna=False)

,count
jobType,
NaN,473
INTERNSHIP,413
PRACTICE,81
JUNIOR,73
TRAINEE,40
SENIOR,23


In [61]:
jobs["verificationStatus"].value_counts(dropna=False)

,count
verificationStatus,
NOT_STARTED,1066
NaN,31
PENDING,5
APPROVED,1


In [62]:
jobs["isExternalOffer"].value_counts(dropna=False)

,count
isExternalOffer,
True,1045
NaN,53
False,5




*   **Exploración básica orientada a calidad de datos en applications**

In [64]:
applications.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 467 entries, 0 to 466
Data columns (total 4 columns):
 #   Column             Non-Null Count  Dtype         
---  ------             --------------  -----         
 0   _id                467 non-null    object        
 1   job                467 non-null    object        
 2   createdAt          466 non-null    datetime64[ns]
 3   applicationStatus  315 non-null    object        
dtypes: datetime64[ns](1), object(3)
memory usage: 14.7+ KB


In [65]:
print(f"Registros: {applications.shape[0]}")
print(f"Columnas: {applications.shape[1]}")

Registros: 467
Columnas: 4


In [66]:
applications.isnull().sum()

,0
_id,0
job,0
createdAt,1
applicationStatus,152


In [67]:
(
    applications.isnull().mean()*100
).round(2).sort_values(ascending=False)

,0
applicationStatus,32.55
createdAt,0.21
job,0.00
_id,0.00


In [68]:
applications["_id"].duplicated().sum()

np.int64(0)

## REALIZAR LA LIMPIEZA DE LOS DATOS







*   **Limpieza de datos en la colección companies**



Paso 1. Verificación de la estructura de los datos

In [69]:
companies.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 83 entries, 0 to 82
Data columns (total 8 columns):
 #   Column              Non-Null Count  Dtype         
---  ------              --------------  -----         
 0   _id                 83 non-null     object        
 1   businessName        18 non-null     object        
 2   industry            43 non-null     object        
 3   verificationStatus  50 non-null     object        
 4   country             18 non-null     object        
 5   plan                67 non-null     object        
 6   isActive            83 non-null     bool          
 7   createdAt           83 non-null     datetime64[ns]
dtypes: bool(1), datetime64[ns](1), object(6)
memory usage: 4.7+ KB


Paso 2.Limpiar espacios

In [70]:
companies_clean = companies.copy()

In [ ]:
columnas_texto = [
    "businessName",
    "industry",
    "verificationStatus",
    "country"
]

for col in columnas_texto:
    companies_clean[col] = companies_clean[col].str.strip()

Paso3.Verificar espacios

In [71]:
companies_clean["country"].value_counts(dropna=False)

,count
country,
NaN,65
Perú,18


In [72]:
companies_clean["industry"].value_counts(dropna=False)

,count
industry,
NaN,40
[],27
Startups / Scaleups,3
Marketing Digital y Social Media,2
EdTech,1
Atención al Cliente y Call Centers (BPO),1
tec,1
[Auditoría y Contabilidad],1
Inteligencia Artificial y Robótica,1


In [73]:
companies_clean["verificationStatus"].value_counts(dropna=False)

,count
verificationStatus,
NOT_STARTED,44
NaN,33
PENDING,3
APPROVED,2
REJECTED,1


3.1 Limpieza de la colección companiesv

In [74]:
companies_clean = companies.copy()
companies_clean.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 83 entries, 0 to 82
Data columns (total 8 columns):
 #   Column              Non-Null Count  Dtype         
---  ------              --------------  -----         
 0   _id                 83 non-null     object        
 1   businessName        18 non-null     object        
 2   industry            43 non-null     object        
 3   verificationStatus  50 non-null     object        
 4   country             18 non-null     object        
 5   plan                67 non-null     object        
 6   isActive            83 non-null     bool          
 7   createdAt           83 non-null     datetime64[ns]
dtypes: bool(1), datetime64[ns](1), object(6)
memory usage: 4.7+ KB


3.2 Eliminación de espacios en blanco

In [75]:
columnas_texto = [
    "businessName",
    "industry",
    "verificationStatus",
    "country"
]

for col in columnas_texto:
    companies_clean[col] = companies_clean[col].str.strip()

Paso 4. Revisión de valores nulos

In [76]:
(
    companies_clean.isnull().sum()
    .to_frame("Nulos")
    .assign(Porcentaje=lambda x: round(x["Nulos"]/len(companies_clean)*100,2))
)

,Nulos,Porcentaje
_id,0,0.00
businessName,65,78.31
industry,70,84.34
verificationStatus,33,39.76
country,65,78.31
plan,16,19.28
isActive,0,0.00
createdAt,0,0.00


Paso 5. Verificación de variables booleanas

In [77]:
companies_clean["isActive"].value_counts(dropna=False)

,count
isActive,
True,83


Paso 6. Revisión del campo plan

In [78]:
companies_clean["plan"].head()

,plan
0,NaN
1,NaN
2,NaN
3,NaN
4,NaN


In [79]:
companies_clean["industry"].value_counts(dropna=False)

,count
industry,
NaN,70
Startups / Scaleups,3
Marketing Digital y Social Media,2
EdTech,1
tec,1
Atención al Cliente y Call Centers (BPO),1
Inteligencia Artificial y Robótica,1
EdTech (Tecnología Educativa),1
Auditoría y Contabilidad,1


Resultado: La variable industry presenta un alto porcentaje de valores nulos: 70 de los 83 registros (84.34%). Solo 13 registros (15.66%) contienen información sobre la industria. Debido a este nivel de incompletitud, no se recomienda utilizar esta variable como indicador principal del dashboard sin realizar previamente un tratamiento adicional de los datos.

In [80]:
companies_clean["verificationStatus"].value_counts(dropna=False)

,count
verificationStatus,
NOT_STARTED,44
NaN,33
PENDING,3
APPROVED,2
REJECTED,1


La variable verificationStatus presenta 34 valores nulos (40.96%). Entre los registros con información, el estado predominante es NOT_STARTED, con 43 registros (51.81%), mientras que PENDING, APPROVED y REJECTED presentan una menor frecuencia. Los valores nulos se conservarán, ya que no se cuenta con información suficiente para determinar el estado de verificación faltante

In [81]:
companies_clean["country"].value_counts(dropna=False)

,count
country,
NaN,65
Perú,18


La variable country presenta 65 valores nulos (78.31%), mientras que los 18 registros que contienen información corresponden a Perú. Debido al alto porcentaje de valores faltantes, la variable presenta una cobertura limitada. No se imputarán los valores nulos, ya que no existe información suficiente para determinar el país de las empresas faltantes.

In [82]:
companies_clean["isActive"].value_counts(dropna=False)

,count
isActive,
True,83


La variable isActive no presenta valores nulos y todos los registros de la colección se encuentran marcados como activos. Por lo tanto, el campo presenta una cobertura completa y puede utilizarse para el análisis del estado de las empresas. Sin embargo, en esta colección no permite diferenciar entre empresas activas e inactivas debido a que todos los registros tienen el valor True.

In [83]:
companies_clean["plan"].head(10)

,plan
0,NaN
1,NaN
2,NaN
3,NaN
4,NaN
5,NaN
6,NaN
7,"{'type': 'FREE_TRIAL', 'freeTrial': {'startedA..."
8,"{'type': 'FREE_TRIAL', 'freeTrial': {'startedA..."
9,NaN


In [84]:
companies_clean["planType"] = companies_clean["plan"].apply(
    lambda x: x.get("type") if isinstance(x, dict) else None
)

In [85]:
companies_clean["planType"].value_counts(dropna=False)

,count
planType,
NONE,34
FREE_TRIAL,33
None,16


In [86]:
companies_clean["planType"] = companies_clean["planType"].replace({
    "None": "NONE"
})

In [87]:
companies_clean["planType"] = companies_clean["planType"].fillna("NONE")

In [88]:
companies_clean["planType"].value_counts(dropna=False)

,count
planType,
NONE,50
FREE_TRIAL,33


Se identificó que 33 empresas (39.76%) cuentan con un plan de prueba gratuita (FREE_TRIAL), mientras que 50 empresas (60.24%) no presentan un plan registrado (NONE). Los valores faltantes fueron estandarizados como NONE para evitar que la ausencia de información se considere una categoría independiente.

*   **Limpieza de datos en la colección jobs**


Paso 1. Verificación de la estructura

In [89]:
jobs_clean = jobs.copy()
jobs_clean.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1103 entries, 0 to 1102
Data columns (total 14 columns):
 #   Column                Non-Null Count  Dtype         
---  ------                --------------  -----         
 0   _id                   1103 non-null   object        
 1   companyId             58 non-null     object        
 2   title                 1103 non-null   object        
 3   department            1096 non-null   object        
 4   modality              1103 non-null   object        
 5   publishUntil          1103 non-null   datetime64[ns]
 6   status                1103 non-null   object        
 7   createdAt             1103 non-null   datetime64[ns]
 8   country               1024 non-null   object        
 9   geographicDepartment  1072 non-null   object        
 10  jobType               630 non-null    object        
 11  verificationStatus    1072 non-null   object        
 12  isExternalOffer       1050 non-null   object        
 13  externalCompanyNam

Paso 2. Limpiar espacios en variables de texto (quitando espacios innecesarios)

In [90]:
columnas_texto_jobs = [
    "title",
    "department",
    "modality",
    "status",
    "country",
    "geographicDepartment",
    "jobType",
    "verificationStatus",
    "externalCompanyName"
]

for col in columnas_texto_jobs:
    jobs_clean[col] = jobs_clean[col].str.strip()

Paso 3. Comprobar modality

In [91]:
jobs_clean["modality"].value_counts(dropna=False)

,count
modality,
presencial,953
hibrido,70
remoto,67
híbrido,13


hibrido y híbrido significan lo mismo, pero están escritos diferente. Si dejamos los datos así, el dashboard mostraría dos categorías de híbrido, lo cual sería incorrecto.

Paso 3.1 — Estandarizar modality

In [92]:
jobs_clean["modality"] = jobs_clean["modality"].replace({
    "hibrido": "híbrido"
})

In [93]:
jobs_clean["modality"].value_counts(dropna=False)

,count
modality,
presencial,953
híbrido,83
remoto,67


Se unificaron ambos valores bajo híbrido, evitando que una misma modalidad aparezca como categorías diferentes en el dashboard.

Paso 4 — Revisar status

In [94]:
jobs_clean["status"].value_counts(dropna=False)

,count
status,
OPEN,903
CLOSED,200


La variable status presenta dos categorías claramente diferenciadas: OPEN y CLOSED. No se identificaron valores nulos ni inconsistencias en su clasificación.

In [95]:
jobs_clean["jobType"].value_counts(dropna=False)

,count
jobType,
NaN,473
INTERNSHIP,413
PRACTICE,81
JUNIOR,73
TRAINEE,40
SENIOR,23


In [96]:
jobs_clean["country"].value_counts(dropna=False)

,count
country,
Perú,1016
NaN,79
Peru,5
,3


Aquí sí conviene hacer una pequeña limpieza, porque Perú y Peru representan el mismo país.

In [97]:
jobs_clean["country"] = jobs_clean["country"].replace({
    "Peru": "Perú"
})

In [98]:
jobs_clean["country"].value_counts(dropna=False)

,count
country,
Perú,1021
NaN,79
,3


In [99]:
jobs_clean["country"].value_counts(dropna=False)

,count
country,
Perú,1021
NaN,79
,3


In [100]:
jobs_clean["country"] = jobs_clean["country"].replace({
    "Peru": "Perú"
})

jobs_clean["country"] = jobs_clean["country"].replace(
    r"^\s*$", np.nan, regex=True
)

In [101]:
jobs_clean["country"].value_counts(dropna=False)

,count
country,
Perú,1021
NaN,82


Los valores faltantes y vacíos se trataron como datos ausentes (NaN), sin realizar imputación, debido a que no existe información suficiente para determinar el país correspondiente.

In [102]:
jobs_clean["geographicDepartment"].value_counts(dropna=False)

,count
geographicDepartment,
Lima,440
Arequipa,247
La Libertad,214
Ica,73
NaN,31
Callao,20
Piura,14
Lambayeque,11
Áncash,10


In [103]:
jobs_clean["geographicDepartment"] = (
    jobs_clean["geographicDepartment"]
    .astype("string")
    .str.strip()
    .replace({"5": np.nan, "": np.nan})
)

In [104]:
jobs_clean["geographicDepartment"].value_counts(dropna=False)

,count
geographicDepartment,
Lima,440
Arequipa,247
La Libertad,214
Ica,73
<NA>,36
Callao,20
Piura,14
Lambayeque,11
Áncash,10


In [105]:
jobs_clean["department"].value_counts(dropna=False)

,count
department,
Marketing,123
Data & Analytics,115
Comercial,87
Contabilidad,63
Administración,56
...,...
Squad Comercial,1
Innovación Tecnológica • Transformación Digital • Ética en IA,1
Proyectos,1


In [106]:
jobs_clean["department"].isna().sum()

np.int64(7)

In [107]:
jobs_clean["department"].value_counts(dropna=False).to_string()

'department\nMarketing                                                                                               123\nData & Analytics                                                                                        115\nComercial                                                                                                87\nContabilidad                                                                                             63\nAdministración                                                                                           56\nFinanzas                                                                                                 24\nAdministración e Ingenierías                                                                             20\nRecursos Humanos                                                                                         18\nPsicología y Administración                                                                              16\nIngeni

In [108]:
jobs_clean["department"].value_counts(dropna=False).to_string()

'department\nMarketing                                                                                               123\nData & Analytics                                                                                        115\nComercial                                                                                                87\nContabilidad                                                                                             63\nAdministración                                                                                           56\nFinanzas                                                                                                 24\nAdministración e Ingenierías                                                                             20\nRecursos Humanos                                                                                         18\nPsicología y Administración                                                                              16\nIngeni

In [109]:
jobs_clean["department"].dropna().unique()

array(['Equivo de Ventas', 'Área de Marketing',
       'Área de Ventas / Comercial', 'Commercial Squad', 'Marketing',
       'Tecnología / Desarrollo de Software', 'Tecnología / Sistemas',
       'Administración', 'Ti', 'Departamento de Cocina', 'Lima',
       'Marketing y Comunicación', 'Operaciones / Tecnología Básica',
       'Proyectos', 'Mantenimiento',
       'Innovación Tecnológica • Transformación Digital • Ética en IA',
       'Tecnología', 'Squad Comercial',
       'Marketing Digital · Transformación Digital · Negocios Digitales',
       'Investigación y desarrollo · Industrial  · Mecánica',
       'Atención al Cliente', 'Data · Data Science · Big Data',
       'Test de departamento', 'Comunicaciones', 'Comercial', 'Gerencia',
       'Tecnología de la Información', 'Gerencia - SIBI',
       'Direccion Ejecutiva', 'Investigación y Desarrollo',
       'Audiovisual, Marketing y Ventas', 'Ventas',
       'Test de Funcionalidades', 'Recursos Humanos', 'Salud', 'prueba',
       'fg

In [110]:
jobs_clean["department"].value_counts(dropna=False).loc[
    ["test", "prueba", "Test de departamento", "Test de Funcionalidades", "fghjklñ", "Lima"]
]

,count
department,
test,1
prueba,1
Test de departamento,3
Test de Funcionalidades,1
fghjklñ,1
Lima,1


Ya podemos tratar esos valores como datos no válidos para department.

In [111]:
valores_invalidos = [
    "test",
    "prueba",
    "Test de departamento",
    "Test de Funcionalidades",
    "fghjklñ",
    "Lima"
]

jobs_clean["department"] = jobs_clean["department"].replace(
    valores_invalidos, np.nan
)

In [112]:
jobs_clean["department"].value_counts(dropna=False).head(20)

,count
department,
Marketing,123
Data & Analytics,115
Comercial,87
Contabilidad,63
Administración,56
Finanzas,24
Administración e Ingenierías,20
Recursos Humanos,18
Psicología y Administración,16


In [113]:
correcciones_department = {
    "Comercia": "Comercial",
    "Contabilidad y Finanzasc": "Contabilidad y Finanzas",
    "Auditoria": "Auditoría",
    "Psicologia": "Psicología",
    "Tecnologia": "Tecnología",
    "Tecnologia / Sistemas": "Tecnología / Sistemas",
    "Tecnologia / TI": "Tecnología / TI",
    "Tecnologia /Soporte Técnico": "Tecnología / Soporte Técnico",
    "Tecnologia / TI , Soporte Técnico": "Tecnología / TI, Soporte Técnico",
    "Tecnologia / Sistemas": "Tecnología / Sistemas",
    "Comunicaciónes": "Comunicaciones",
    "Comunicacion": "Comunicación",
    "Diseño Grafico": "Diseño Gráfico",
    "Diseño gráfico": "Diseño Gráfico",
    "Mineria": "Minería",
    "Atención al cliente": "Atención al Cliente",
    "Trabajo social": "Trabajo Social",
    "Administración y Finanzas.": "Administración y Finanzas",
    "Administración y Oficina.": "Administración y Oficina",
    "Logística y Cadena de Suministro.": "Logística y Cadena de Suministro",
    "Tecnología e Innovación.": "Tecnología e Innovación",
    "Seguridad Industrial / SSOMA.": "Seguridad Industrial / SSOMA",
    "Ingeniería Industrial y Operaciones.": "Ingeniería Industrial y Operaciones",
    "Electricidad Industrial, Electrotecnia o Electricidad.": "Electricidad Industrial, Electrotecnia o Electricidad",
    "Energía y Electricidad.": "Energía y Electricidad",
    "Mantenimiento Eléctrico Industrial.": "Mantenimiento Eléctrico Industrial",
}

jobs_clean["department"] = jobs_clean["department"].replace(correcciones_department)

In [114]:
jobs_clean["department"].value_counts(dropna=False)

,count
department,
Marketing,123
Data & Analytics,115
Comercial,88
Contabilidad,63
Administración,56
...,...
"Administración, Comercial",1
Planeamiento Comercial,1
Inteligencia Comercial,1


In [115]:
jobs_clean["department"].isna().sum()

np.int64(15)

In [116]:
jobs_clean["verificationStatus"].value_counts(dropna=False)

,count
verificationStatus,
NOT_STARTED,1066
NaN,31
PENDING,5
APPROVED,1


No se encontraron inconsistencias de formato o categorías claramente inválidas, por lo que la variable se conserva sin modificaciones y los valores faltantes se mantienen como NaN.

In [117]:
jobs_clean["isExternalOffer"].value_counts(dropna=False)

,count
isExternalOffer,
True,1045
NaN,53
False,5


In [118]:
jobs_clean["externalCompanyName"].value_counts(dropna=False)

,count
externalCompanyName,
NaN,58
Caja Arequipa,24
CAJA TRUJILLO,19
Bitel,17
ManpowerGroup Perú,14
...,...
DIGITALNOVA INVERSIONES S.A.C.S.,1
Atento Perú,1
Grupo Alina corp,1


In [119]:
jobs_clean["createdAt"].head()

,createdAt
0,2025-11-10 16:55:55.029
1,2025-11-27 00:12:18.476
2,2025-11-27 00:35:48.105
3,2025-11-27 00:39:59.268
4,2025-11-27 00:46:16.849


In [120]:
jobs_clean["createdAt"].isna().sum()

np.int64(0)

In [121]:
jobs_clean["createdAt"].dtype

dtype('<M8[ns]')

In [122]:
jobs_clean["publishUntil"].head()

,publishUntil
0,2025-11-11
1,2025-12-20
2,2025-12-20
3,2025-12-20
4,2025-12-20


In [123]:
jobs_clean["publishUntil"].dtype

dtype('<M8[ns]')

In [124]:
jobs_clean["publishUntil"].isna().sum()

np.int64(0)

In [125]:
(jobs_clean["publishUntil"] < jobs_clean["createdAt"]).sum()

np.int64(1)

In [126]:
jobs_clean.loc[
    jobs_clean["publishUntil"] < jobs_clean["createdAt"],
    ["createdAt", "publishUntil"]
]

,createdAt,publishUntil
449,2026-07-21 01:33:24.539,2026-07-17


In [127]:
jobs_clean.shape

(1103, 14)

In [128]:
jobs_clean.loc[449]

,449
_id,6a5ecc649e10ebf257a0baf8
companyId,None
title,Practicante de Recursos Humanos ( Innovación)
department,Tecnología e Innovación
modality,presencial
publishUntil,2026-07-17 00:00:00
status,CLOSED
createdAt,2026-07-21 01:33:24.539000
country,Perú
geographicDepartment,Arequipa


In [129]:
jobs_clean.loc[449]

,449
_id,6a5ecc649e10ebf257a0baf8
companyId,None
title,Practicante de Recursos Humanos ( Innovación)
department,Tecnología e Innovación
modality,presencial
publishUntil,2026-07-17 00:00:00
status,CLOSED
createdAt,2026-07-21 01:33:24.539000
country,Perú
geographicDepartment,Arequipa


Se identificó un registro con una inconsistencia temporal, donde la fecha de finalización de publicación era anterior a la fecha de creación de la oferta. Debido a que no fue posible determinar cuál de las fechas era correcta, se eliminó dicho registro para evitar distorsiones en el análisis temporal.

In [130]:
jobs_clean = jobs_clean.drop(index=449)

In [131]:
print(jobs_clean.shape)
print((jobs_clean["publishUntil"] < jobs_clean["createdAt"]).sum())

(1102, 14)
0


El siguiente paso lógico es revisar los valores faltantes de todas las columnas:

In [132]:
jobs_clean.isnull().sum()

,0
_id,0
companyId,1044
title,0
department,15
modality,0
publishUntil,0
status,0
createdAt,0
country,82
geographicDepartment,36


In [133]:
jobs_clean["companyId"].isna().groupby(jobs_clean["isExternalOffer"]).sum()

,companyId
isExternalOffer,
False,0
True,1044


In [134]:
jobs_clean["jobType"].value_counts(dropna=False)

,count
jobType,
NaN,472
INTERNSHIP,413
PRACTICE,81
JUNIOR,73
TRAINEE,40
SENIOR,23


In [135]:
pd.crosstab(
    jobs_clean["isExternalOffer"],
    jobs_clean["companyId"].isna()
)

companyId,False,True
isExternalOffer,,
False,5,0
True,0,1044


In [136]:
jobs_clean["isExternalOffer"].value_counts(dropna=False)

,count
isExternalOffer,
True,1044
NaN,53
False,5


La columna isExternalOffer indica si la oferta laboral es externa a la plataforma o no.

In [137]:
jobs_clean.isnull().sum().to_frame("Nulos").assign(
    Porcentaje=lambda x: round(x["Nulos"] / len(jobs_clean) * 100, 2)
)

,Nulos,Porcentaje
_id,0,0.00
companyId,1044,94.74
title,0,0.00
department,15,1.36
modality,0,0.00
publishUntil,0,0.00
status,0,0.00
createdAt,0,0.00
country,82,7.44
geographicDepartment,36,3.27


companyId presenta 94.71% de valores nulos, estos valores son consistentes con la estructura de los datos, ya que corresponden a ofertas externas que no están asociadas a una empresa registrada mediante este identificador.

In [138]:
jobs_clean["jobType"].value_counts(dropna=False)

,count
jobType,
NaN,472
INTERNSHIP,413
PRACTICE,81
JUNIOR,73
TRAINEE,40
SENIOR,23


In [139]:
jobs_clean["isExternalOffer"].value_counts(dropna=False)

,count
isExternalOffer,
True,1044
NaN,53
False,5


In [140]:
pd.crosstab(
    jobs_clean["isExternalOffer"],
    jobs_clean["companyId"].isna()
)

companyId,False,True
isExternalOffer,,
False,5,0
True,0,1044


In [141]:
jobs_clean.loc[
    jobs_clean["isExternalOffer"].isna(),
    ["companyId", "externalCompanyName", "title", "country"]
]

,companyId,externalCompanyName,title,country
0,69120eb074d1880032cff302,NaN,Practicante Comercial Ecommerce,NaN
1,692790216dc39bf20c52f5f5,NaN,Practicante de Growth & Experimentos de Produc...,NaN
2,692790216dc39bf20c52f5f5,NaN,Practicante de Marketing y Contenido Orgánico ...,NaN
3,692790216dc39bf20c52f5f5,NaN,Asesor Comercial B2B de Software | Part Time,NaN
4,692790216dc39bf20c52f5f5,NaN,Trafficker Digital | Full Time,NaN
5,692f56d3aafd375d6d269ff1,NaN,Ejecutivo Comercial Junior (Outbound),Perú
6,693da1713d5cc7809ad56001,NaN,Practicante,NaN
7,694567c6c8f58b252bb6be38,NaN,Desarrollador/a Frontend Jr,NaN
8,694589acc8f58b252bb6c0e0,NaN,Desarrollador Web Junior,NaN
9,69458d62c8f58b252bb6c1cf,NaN,Auxiliar Administrativo (Prueba),NaN


In [142]:
(
    jobs_clean.isnull().sum()
    .to_frame("Nulos")
    .assign(
        Porcentaje=lambda x: round(
            x["Nulos"] / len(jobs_clean) * 100, 2
        )
    )
)

,Nulos,Porcentaje
_id,0,0.00
companyId,1044,94.74
title,0,0.00
department,15,1.36
modality,0,0.00
publishUntil,0,0.00
status,0,0.00
createdAt,0,0.00
country,82,7.44
geographicDepartment,36,3.27


In [143]:
jobs_clean.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1102 entries, 0 to 1102
Data columns (total 14 columns):
 #   Column                Non-Null Count  Dtype         
---  ------                --------------  -----         
 0   _id                   1102 non-null   object        
 1   companyId             58 non-null     object        
 2   title                 1102 non-null   object        
 3   department            1087 non-null   object        
 4   modality              1102 non-null   object        
 5   publishUntil          1102 non-null   datetime64[ns]
 6   status                1102 non-null   object        
 7   createdAt             1102 non-null   datetime64[ns]
 8   country               1020 non-null   object        
 9   geographicDepartment  1066 non-null   string        
 10  jobType               630 non-null    object        
 11  verificationStatus    1071 non-null   object        
 12  isExternalOffer       1049 non-null   object        
 13  externalCompanyName   1

In [144]:
jobs_clean = jobs_clean.reset_index(drop=True)

*   **Limpieza de datos en la colección jobs**


In [145]:
applications_clean = applications.copy()

In [146]:
applications_clean.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 467 entries, 0 to 466
Data columns (total 4 columns):
 #   Column             Non-Null Count  Dtype         
---  ------             --------------  -----         
 0   _id                467 non-null    object        
 1   job                467 non-null    object        
 2   createdAt          466 non-null    datetime64[ns]
 3   applicationStatus  315 non-null    object        
dtypes: datetime64[ns](1), object(3)
memory usage: 14.7+ KB


In [147]:
applications_clean.head()

,_id,job,createdAt,applicationStatus
0,6917cdf4998d66b34dac075b,6917cd88998d66b34dac0734,2025-11-15 00:48:52.932,NaN
1,692867743b4884927933f66e,692797626dc39bf20c52f60f,2025-11-27 15:00:04.307,NaN
2,6928ab6e985136edda36ae82,69279ce46dc39bf20c52f61c,2025-11-27 19:50:06.623,NaN
3,692a2b217f1f3ab5036abc0d,69279ddf6dc39bf20c52f62f,2025-11-28 23:07:13.054,NaN
4,692a5c537f1f3ab5036abe21,69279ce46dc39bf20c52f61c,2025-11-29 02:37:07.991,NaN


2.1 Revisar applicationStatus

In [148]:
applications_clean["applicationStatus"].value_counts(dropna=False)

,count
applicationStatus,
ENVIADO,209
NaN,152
EN_REVISION,64
SELECCIONADO,25
DESCARTADO,12
RETIRADO,4
ENTREVISTA,1


2.2 Revisar job

In [149]:
applications_clean["job"].head(10)

,job
0,6917cd88998d66b34dac0734
1,692797626dc39bf20c52f60f
2,69279ce46dc39bf20c52f61c
3,69279ddf6dc39bf20c52f62f
4,69279ce46dc39bf20c52f61c
5,69279ce46dc39bf20c52f61c
6,69279ddf6dc39bf20c52f62f
7,69279ce46dc39bf20c52f61c
8,69279f586dc39bf20c52f64b
9,69279ce46dc39bf20c52f61c


2.3 Revisar createdAt

In [150]:
applications_clean["createdAt"].describe()

,createdAt
count,466
mean,2026-03-28 17:27:46.730866944
min,2025-11-15 00:48:52.932000
25%,2026-02-12 14:24:10.341249792
50%,2026-04-22 13:31:20.845999872
75%,2026-05-22 18:55:36.157250048
max,2026-07-15 22:04:33.185000


In [151]:
applications_clean["createdAt"].isna().sum()

np.int64(1)

In [152]:
applications_clean[applications_clean["createdAt"].isna()]

,_id,job,createdAt,applicationStatus
124,69957bec7483f05f9810e9a1,6995758e2b34b6358a0c4a18,NaT,NaN


In [153]:
applications_clean.loc[
    applications_clean["_id"] == "69957bec7483f05f9810e9a1"
]

,_id,job,createdAt,applicationStatus


In [154]:
applications[applications["_id"] == "69957bec7483f05f9810e9a1"]

,_id,job,createdAt,applicationStatus


In [155]:
applications_clean["applicationStatus"].value_counts(dropna=False)

,count
applicationStatus,
ENVIADO,209
NaN,152
EN_REVISION,64
SELECCIONADO,25
DESCARTADO,12
RETIRADO,4
ENTREVISTA,1


In [156]:
status_grafico = applications_clean["applicationStatus"].fillna("SIN_ESTADO")

In [157]:
applications_clean.isna().sum()

,0
_id,0
job,0
createdAt,1
applicationStatus,152


In [158]:
applications_clean.shape

(467, 4)

## CRUZAR TABLAS NECESARIAS


El cruce de tablas consiste en relacionar dos o más colecciones que tienen un campo en común, para combinar su información y poder analizarlas juntas como si fuera una tabla más completa.

Colección A + campo en común + Colección B = información relacionada

In [159]:

# Mostrar los DataFrames que terminan en "_clean"
[x for x in globals() if x.endswith("_clean")]

['companies_clean', 'jobs_clean', 'applications_clean']

In [160]:
print("=== COMPANIES ===")
print(companies_clean.columns.tolist())

print("\n=== JOBS ===")
print(jobs_clean.columns.tolist())

print("\n=== APPLICATIONS ===")
print(applications_clean.columns.tolist())

=== COMPANIES ===
['_id', 'businessName', 'industry', 'verificationStatus', 'country', 'plan', 'isActive', 'createdAt', 'planType']

=== JOBS ===
['_id', 'companyId', 'title', 'department', 'modality', 'publishUntil', 'status', 'createdAt', 'country', 'geographicDepartment', 'jobType', 'verificationStatus', 'isExternalOffer', 'externalCompanyName']

=== APPLICATIONS ===
['_id', 'job', 'createdAt', 'applicationStatus']


Usamos la relación de colecciones que se hizo en el DER peor antes verificamos si los datos de las columnas son lo mismo.

In [161]:
# Comprobar relación: companies → jobs

company_ids = set(companies_clean['_id'].dropna().astype(str))
job_company_ids = set(jobs_clean['companyId'].dropna().astype(str))

coincidencias = company_ids.intersection(job_company_ids)

print("IDs de empresas:", len(company_ids))
print("IDs de empresas usados en jobs:", len(job_company_ids))
print("Coincidencias:", len(coincidencias))

IDs de empresas: 83
IDs de empresas usados en jobs: 40
Coincidencias: 29


In [162]:
# Comprobar relación: jobs → applications

job_ids = set(jobs_clean['_id'].dropna().astype(str))
application_job_ids = set(applications_clean['job'].dropna().astype(str))

coincidencias_jobs = job_ids.intersection(application_job_ids)

print("IDs de jobs:", len(job_ids))
print("IDs de jobs usados en applications:", len(application_job_ids))
print("Coincidencias:", len(coincidencias_jobs))

IDs de jobs: 1102
IDs de jobs usados en applications: 46
Coincidencias: 43


In [163]:
# Verificar las postulaciones que tienen un job válido

applications_clean['job'].astype(str).isin(
    jobs_clean['_id'].astype(str)
).value_counts()

,count
job,
True,462
False,5


In [164]:
applications_jobs = applications_clean.merge(
    jobs_clean,
    left_on='job',
    right_on='_id',
    how='left',
    suffixes=('_application', '_job')
)

print("Filas:", applications_jobs.shape[0])
print("Columnas:", applications_jobs.shape[1])

Filas: 467
Columnas: 18


In [165]:
applications_jobs.head()

,_id_application,job,createdAt_application,applicationStatus,_id_job,companyId,title,department,modality,publishUntil,status,createdAt_job,country,geographicDepartment,jobType,verificationStatus,isExternalOffer,externalCompanyName
0,6917cdf4998d66b34dac075b,6917cd88998d66b34dac0734,2025-11-15 00:48:52.932,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaT,NaN,<NA>,NaN,NaN,NaN,NaN
1,692867743b4884927933f66e,692797626dc39bf20c52f60f,2025-11-27 15:00:04.307,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaT,NaN,<NA>,NaN,NaN,NaN,NaN
2,6928ab6e985136edda36ae82,69279ce46dc39bf20c52f61c,2025-11-27 19:50:06.623,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaT,NaN,<NA>,NaN,NaN,NaN,NaN
3,692a2b217f1f3ab5036abc0d,69279ddf6dc39bf20c52f62f,2025-11-28 23:07:13.054,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaT,NaN,<NA>,NaN,NaN,NaN,NaN
4,692a5c537f1f3ab5036abe21,69279ce46dc39bf20c52f61c,2025-11-29 02:37:07.991,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaT,NaN,<NA>,NaN,NaN,NaN,NaN


In [166]:
print("Tipo de applications_clean['job']:")
print(applications_clean['job'].dtype)

print("\nTipo de jobs_clean['_id']:")
print(jobs_clean['_id'].dtype)

Tipo de applications_clean['job']:
object

Tipo de jobs_clean['_id']:
object


In [167]:
print("\nEjemplo de job en applications:")
print(applications_clean['job'].dropna().iloc[0])

print("\nEjemplo de _id en jobs:")
print(jobs_clean['_id'].dropna().iloc[0])


Ejemplo de job en applications:
6917cd88998d66b34dac0734

Ejemplo de _id en jobs:
6912191b74d1880032cff34f


In [168]:
# Tomamos el primer job de una postulación
job_ejemplo = applications_clean['job'].dropna().iloc[0]

print("Job de la postulación:")
print(repr(job_ejemplo))

print("\n¿Existe exactamente en jobs_clean?")
print(job_ejemplo in jobs_clean['_id'].values)

Job de la postulación:
'6917cd88998d66b34dac0734'

¿Existe exactamente en jobs_clean?
False


In [169]:
# Buscar ese job directamente en jobs_clean
jobs_clean[jobs_clean['_id'] == job_ejemplo]

,_id,companyId,title,department,modality,publishUntil,status,createdAt,country,geographicDepartment,jobType,verificationStatus,isExternalOffer,externalCompanyName


In [170]:
# Encontrar un job de una postulación que sí exista en jobs_clean

jobs_ids = set(jobs_clean['_id'].astype(str))

coincidentes = applications_clean[
    applications_clean['job'].astype(str).isin(jobs_ids)
]

print("Postulaciones con job coincidente:", len(coincidentes))

print("\nPrimeras 5 coincidencias:")
print(coincidentes[['job', 'applicationStatus']].head())

Postulaciones con job coincidente: 462

Primeras 5 coincidencias:
                        job applicationStatus
1  692797626dc39bf20c52f60f               NaN
2  69279ce46dc39bf20c52f61c               NaN
3  69279ddf6dc39bf20c52f62f               NaN
4  69279ce46dc39bf20c52f61c               NaN
5  69279ce46dc39bf20c52f61c               NaN


Corregimos el primer cruce

In [171]:
applications_jobs = applications_clean.merge(
    jobs_clean,
    left_on=applications_clean['job'].astype(str),
    right_on=jobs_clean['_id'].astype(str),
    how='left',
    suffixes=('_application', '_job')
)

print("Filas:", applications_jobs.shape[0])
print("Columnas:", applications_jobs.shape[1])

Filas: 467
Columnas: 19


Contiene información de postulación + oferta laboral.

In [172]:
applications_jobs.head()

,key_0,_id_application,job,createdAt_application,applicationStatus,_id_job,companyId,title,department,modality,publishUntil,status,createdAt_job,country,geographicDepartment,jobType,verificationStatus,isExternalOffer,externalCompanyName
0,6917cd88998d66b34dac0734,6917cdf4998d66b34dac075b,6917cd88998d66b34dac0734,2025-11-15 00:48:52.932,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaT,NaN,<NA>,NaN,NaN,NaN,NaN
1,692797626dc39bf20c52f60f,692867743b4884927933f66e,692797626dc39bf20c52f60f,2025-11-27 15:00:04.307,NaN,692797626dc39bf20c52f60f,692790216dc39bf20c52f5f5,Practicante de Growth & Experimentos de Produc...,Área de Marketing,híbrido,2025-12-20,CLOSED,2025-11-27 00:12:18.476,NaN,<NA>,NaN,NaN,NaN,NaN
2,69279ce46dc39bf20c52f61c,6928ab6e985136edda36ae82,69279ce46dc39bf20c52f61c,2025-11-27 19:50:06.623,NaN,69279ce46dc39bf20c52f61c,692790216dc39bf20c52f5f5,Practicante de Marketing y Contenido Orgánico ...,Área de Marketing,híbrido,2025-12-20,CLOSED,2025-11-27 00:35:48.105,NaN,<NA>,NaN,NaN,NaN,NaN
3,69279ddf6dc39bf20c52f62f,692a2b217f1f3ab5036abc0d,69279ddf6dc39bf20c52f62f,2025-11-28 23:07:13.054,NaN,69279ddf6dc39bf20c52f62f,692790216dc39bf20c52f5f5,Asesor Comercial B2B de Software | Part Time,Área de Ventas / Comercial,híbrido,2025-12-20,CLOSED,2025-11-27 00:39:59.268,NaN,<NA>,NaN,NaN,NaN,NaN
4,69279ce46dc39bf20c52f61c,692a5c537f1f3ab5036abe21,69279ce46dc39bf20c52f61c,2025-11-29 02:37:07.991,NaN,69279ce46dc39bf20c52f61c,692790216dc39bf20c52f5f5,Practicante de Marketing y Contenido Orgánico ...,Área de Marketing,híbrido,2025-12-20,CLOSED,2025-11-27 00:35:48.105,NaN,<NA>,NaN,NaN,NaN,NaN


Se elimino la columnna llamada key_0

In [173]:
applications_jobs = applications_jobs.drop(columns=['key_0'])

applications_jobs.head()

,_id_application,job,createdAt_application,applicationStatus,_id_job,companyId,title,department,modality,publishUntil,status,createdAt_job,country,geographicDepartment,jobType,verificationStatus,isExternalOffer,externalCompanyName
0,6917cdf4998d66b34dac075b,6917cd88998d66b34dac0734,2025-11-15 00:48:52.932,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaT,NaN,<NA>,NaN,NaN,NaN,NaN
1,692867743b4884927933f66e,692797626dc39bf20c52f60f,2025-11-27 15:00:04.307,NaN,692797626dc39bf20c52f60f,692790216dc39bf20c52f5f5,Practicante de Growth & Experimentos de Produc...,Área de Marketing,híbrido,2025-12-20,CLOSED,2025-11-27 00:12:18.476,NaN,<NA>,NaN,NaN,NaN,NaN
2,6928ab6e985136edda36ae82,69279ce46dc39bf20c52f61c,2025-11-27 19:50:06.623,NaN,69279ce46dc39bf20c52f61c,692790216dc39bf20c52f5f5,Practicante de Marketing y Contenido Orgánico ...,Área de Marketing,híbrido,2025-12-20,CLOSED,2025-11-27 00:35:48.105,NaN,<NA>,NaN,NaN,NaN,NaN
3,692a2b217f1f3ab5036abc0d,69279ddf6dc39bf20c52f62f,2025-11-28 23:07:13.054,NaN,69279ddf6dc39bf20c52f62f,692790216dc39bf20c52f5f5,Asesor Comercial B2B de Software | Part Time,Área de Ventas / Comercial,híbrido,2025-12-20,CLOSED,2025-11-27 00:39:59.268,NaN,<NA>,NaN,NaN,NaN,NaN
4,692a5c537f1f3ab5036abe21,69279ce46dc39bf20c52f61c,2025-11-29 02:37:07.991,NaN,69279ce46dc39bf20c52f61c,692790216dc39bf20c52f5f5,Practicante de Marketing y Contenido Orgánico ...,Área de Marketing,híbrido,2025-12-20,CLOSED,2025-11-27 00:35:48.105,NaN,<NA>,NaN,NaN,NaN,NaN


In [174]:
applications_jobs.columns.tolist()

['_id_application',
 'job',
 'createdAt_application',
 'applicationStatus',
 '_id_job',
 'companyId',
 'title',
 'department',
 'modality',
 'publishUntil',
 'status',
 'createdAt_job',
 'country',
 'geographicDepartment',
 'jobType',
 'verificationStatus',
 'isExternalOffer',
 'externalCompanyName']

Segundo cruce

Primero, igual que hicimos antes, vamos a comprobar que los companyId del DataFrame cruzado realmente coincidan con las empresas.

In [175]:
# Comprobar relación: applications_jobs → companies

company_ids = set(
    companies_clean['_id'].dropna().astype(str)
)

job_company_ids = set(
    applications_jobs['companyId'].dropna().astype(str)
)

coincidencias_companies = company_ids.intersection(job_company_ids)

print("IDs de empresas:", len(company_ids))
print("IDs de empresas usados en applications_jobs:", len(job_company_ids))
print("Coincidencias:", len(coincidencias_companies))

IDs de empresas: 83
IDs de empresas usados en applications_jobs: 31
Coincidencias: 22


In [176]:
applications_jobs_companies = applications_jobs.merge(
    companies_clean,
    left_on=applications_jobs['companyId'].astype(str),
    right_on=companies_clean['_id'].astype(str),
    how='left',
    suffixes=('', '_company')
)

print("Filas:", applications_jobs_companies.shape[0])
print("Columnas:", applications_jobs_companies.shape[1])

Filas: 467
Columnas: 28


In [177]:
applications_jobs_companies.head()

,key_0,_id_application,job,createdAt_application,applicationStatus,_id_job,companyId,title,department,modality,...,externalCompanyName,_id,businessName,industry,verificationStatus_company,country_company,plan,isActive,createdAt,planType
0,nan,6917cdf4998d66b34dac075b,6917cd88998d66b34dac0734,2025-11-15 00:48:52.932,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN
1,692790216dc39bf20c52f5f5,692867743b4884927933f66e,692797626dc39bf20c52f60f,2025-11-27 15:00:04.307,NaN,692797626dc39bf20c52f60f,692790216dc39bf20c52f5f5,Practicante de Growth & Experimentos de Produc...,Área de Marketing,híbrido,...,NaN,692790216dc39bf20c52f5f5,NaN,NaN,NaN,NaN,"{'type': 'FREE_TRIAL', 'freeTrial': {'startedA...",True,2025-11-26 23:41:21.773,FREE_TRIAL
2,692790216dc39bf20c52f5f5,6928ab6e985136edda36ae82,69279ce46dc39bf20c52f61c,2025-11-27 19:50:06.623,NaN,69279ce46dc39bf20c52f61c,692790216dc39bf20c52f5f5,Practicante de Marketing y Contenido Orgánico ...,Área de Marketing,híbrido,...,NaN,692790216dc39bf20c52f5f5,NaN,NaN,NaN,NaN,"{'type': 'FREE_TRIAL', 'freeTrial': {'startedA...",True,2025-11-26 23:41:21.773,FREE_TRIAL
3,692790216dc39bf20c52f5f5,692a2b217f1f3ab5036abc0d,69279ddf6dc39bf20c52f62f,2025-11-28 23:07:13.054,NaN,69279ddf6dc39bf20c52f62f,692790216dc39bf20c52f5f5,Asesor Comercial B2B de Software | Part Time,Área de Ventas / Comercial,híbrido,...,NaN,692790216dc39bf20c52f5f5,NaN,NaN,NaN,NaN,"{'type': 'FREE_TRIAL', 'freeTrial': {'startedA...",True,2025-11-26 23:41:21.773,FREE_TRIAL
4,692790216dc39bf20c52f5f5,692a5c537f1f3ab5036abe21,69279ce46dc39bf20c52f61c,2025-11-29 02:37:07.991,NaN,69279ce46dc39bf20c52f61c,692790216dc39bf20c52f5f5,Practicante de Marketing y Contenido Orgánico ...,Área de Marketing,híbrido,...,NaN,692790216dc39bf20c52f5f5,NaN,NaN,NaN,NaN,"{'type': 'FREE_TRIAL', 'freeTrial': {'startedA...",True,2025-11-26 23:41:21.773,FREE_TRIAL


Eliminamod la columna creada anteriormnete: key_0

In [178]:
applications_jobs_companies = applications_jobs_companies.drop(
    columns=['key_0']
)

print("Filas:", applications_jobs_companies.shape[0])
print("Columnas:", applications_jobs_companies.shape[1])

Filas: 467
Columnas: 27


In [179]:
applications_jobs_companies.columns.tolist()

['_id_application',
 'job',
 'createdAt_application',
 'applicationStatus',
 '_id_job',
 'companyId',
 'title',
 'department',
 'modality',
 'publishUntil',
 'status',
 'createdAt_job',
 'country',
 'geographicDepartment',
 'jobType',
 'verificationStatus',
 'isExternalOffer',
 'externalCompanyName',
 '_id',
 'businessName',
 'industry',
 'verificationStatus_company',
 'country_company',
 'plan',
 'isActive',
 'createdAt',
 'planType']

¿Cuántas postulaciones tienen información de la oferta?

In [180]:
print("Postulaciones totales:", len(applications_jobs_companies))

print(
    "Postulaciones con oferta:",
    applications_jobs_companies['_id_job'].notna().sum()
)

print(
    "Postulaciones sin oferta:",
    applications_jobs_companies['_id_job'].isna().sum()
)

Postulaciones totales: 467
Postulaciones con oferta: 462
Postulaciones sin oferta: 5


¿Cuántas tienen información de empresa?

In [181]:
print(
    "Postulaciones con empresa:",
    applications_jobs_companies['businessName'].notna().sum()
)

print(
    "Postulaciones sin empresa:",
    applications_jobs_companies['businessName'].isna().sum()
)

Postulaciones con empresa: 126
Postulaciones sin empresa: 341


In [182]:
applications_jobs_companies[
    applications_jobs_companies['businessName'].isna()
][
    ['_id_application',
     'job',
     '_id_job',
     'companyId',
     'isExternalOffer',
     'externalCompanyName']
].head(20)

,_id_application,job,_id_job,companyId,isExternalOffer,externalCompanyName
0,6917cdf4998d66b34dac075b,6917cd88998d66b34dac0734,NaN,NaN,NaN,NaN
1,692867743b4884927933f66e,692797626dc39bf20c52f60f,692797626dc39bf20c52f60f,692790216dc39bf20c52f5f5,NaN,NaN
2,6928ab6e985136edda36ae82,69279ce46dc39bf20c52f61c,69279ce46dc39bf20c52f61c,692790216dc39bf20c52f5f5,NaN,NaN
3,692a2b217f1f3ab5036abc0d,69279ddf6dc39bf20c52f62f,69279ddf6dc39bf20c52f62f,692790216dc39bf20c52f5f5,NaN,NaN
4,692a5c537f1f3ab5036abe21,69279ce46dc39bf20c52f61c,69279ce46dc39bf20c52f61c,692790216dc39bf20c52f5f5,NaN,NaN
5,69308e2b53aa614862331c3b,69279ce46dc39bf20c52f61c,69279ce46dc39bf20c52f61c,692790216dc39bf20c52f5f5,NaN,NaN
6,69308e5f53aa614862331c57,69279ddf6dc39bf20c52f62f,69279ddf6dc39bf20c52f62f,692790216dc39bf20c52f5f5,NaN,NaN
7,693090a753aa614862331d66,69279ce46dc39bf20c52f61c,69279ce46dc39bf20c52f61c,692790216dc39bf20c52f5f5,NaN,NaN
8,693090e553aa614862331d90,69279f586dc39bf20c52f64b,69279f586dc39bf20c52f64b,692790216dc39bf20c52f5f5,NaN,NaN
9,6930978d53aa614862331eae,69279ce46dc39bf20c52f61c,69279ce46dc39bf20c52f61c,692790216dc39bf20c52f5f5,NaN,NaN


In [183]:
applications_jobs_companies[
    applications_jobs_companies['businessName'].isna()
]['isExternalOffer'].value_counts(dropna=False)

,count
isExternalOffer,
NaN,341


In [184]:
jobs_clean[
    jobs_clean['_id'].astype(str).isin(
        applications_clean['job'].astype(str)
    )
][
    ['_id', 'companyId', 'isExternalOffer', 'externalCompanyName']
].head(20)

,_id,companyId,isExternalOffer,externalCompanyName
0,6912191b74d1880032cff34f,69120eb074d1880032cff302,NaN,NaN
1,692797626dc39bf20c52f60f,692790216dc39bf20c52f5f5,NaN,NaN
2,69279ce46dc39bf20c52f61c,692790216dc39bf20c52f5f5,NaN,NaN
3,69279ddf6dc39bf20c52f62f,692790216dc39bf20c52f5f5,NaN,NaN
4,69279f586dc39bf20c52f64b,692790216dc39bf20c52f5f5,NaN,NaN
5,692f5830aafd375d6d269ffb,692f56d3aafd375d6d269ff1,NaN,NaN
7,69456d6cc8f58b252bb6be52,694567c6c8f58b252bb6be38,NaN,NaN
8,69458be7c8f58b252bb6c1a0,694589acc8f58b252bb6c0e0,NaN,NaN
9,69458f4cc8f58b252bb6c1f2,69458d62c8f58b252bb6c1cf,NaN,NaN
10,6945949cc8f58b252bb6c353,6945940ac8f58b252bb6c317,NaN,NaN


Identificamos cuáles son esos 9 companyId que aparecen en jobs_clean, pero no existen en companies_clean.

In [185]:
# IDs de empresas registradas
company_ids = set(companies_clean['_id'].astype(str))

# IDs de empresa usados por los jobs con postulaciones
job_company_ids = set(
    jobs_clean[
        jobs_clean['_id'].astype(str).isin(
            applications_clean['job'].astype(str)
        )
    ]['companyId'].dropna().astype(str)
)

# Empresas referenciadas pero no encontradas
company_ids_faltantes = job_company_ids - company_ids

print("CompanyId no encontrados:", len(company_ids_faltantes))
print("\nIDs:")
print(company_ids_faltantes)

CompanyId no encontrados: 9

IDs:
{'694700101bbcac95cc041e50', '6945940ac8f58b252bb6c317', '694567c6c8f58b252bb6be38', '694f27f9a00c93fb63efd1ca', '69e66844239f20d09d9774a6', '6912a0df74d1880032cff5ad', '69458d62c8f58b252bb6c1cf', '694589acc8f58b252bb6c0e0', '694c224bd2c9099891aebef6'}


In [186]:
jobs_company_faltantes = jobs_clean[
    jobs_clean['companyId'].astype(str).isin(company_ids_faltantes)
][[
    '_id',
    'companyId',
    'title',
    'isExternalOffer',
    'externalCompanyName',
    'status'
]]

jobs_company_faltantes

,_id,companyId,title,isExternalOffer,externalCompanyName,status
7,69456d6cc8f58b252bb6be52,694567c6c8f58b252bb6be38,Desarrollador/a Frontend Jr,NaN,NaN,CLOSED
8,69458be7c8f58b252bb6c1a0,694589acc8f58b252bb6c0e0,Desarrollador Web Junior,NaN,NaN,CLOSED
9,69458f4cc8f58b252bb6c1f2,69458d62c8f58b252bb6c1cf,Auxiliar Administrativo (Prueba),NaN,NaN,CLOSED
10,6945949cc8f58b252bb6c353,6945940ac8f58b252bb6c317,Desarrollador web,NaN,NaN,CLOSED
11,694700691bbcac95cc041e58,694700101bbcac95cc041e50,Desarrollador Junior de Software,NaN,NaN,CLOSED
14,694c2433d2c9099891aebefe,694c224bd2c9099891aebef6,Analista de Marketing Digital Senior,NaN,NaN,CLOSED
15,694f54b7a00c93fb63efd208,694f27f9a00c93fb63efd1ca,Auxiliar de Digitalización y Organización de D...,NaN,NaN,CLOSED
18,6961424db045cb8f35aad40c,6912a0df74d1880032cff5ad,Test,NaN,NaN,CLOSED
44,69e66e84239f20d09d977811,69e66844239f20d09d9774a6,Asesor (a) comercial de seguros de Vida,NaN,NaN,CLOSED


Se identificaron 9 companyId referenciados en la colección jobs que no presentan correspondencia en la colección companies. Estos registros no están marcados como ofertas externas, por lo que se consideran referencias de empresa no resueltas y requieren revisión de integridad de datos.

Primero queremos saber si el cruce generó registros duplicados.

In [187]:
# Revisar si una misma postulación aparece más de una vez

duplicados_app = applications_jobs_companies['_id_application'].duplicated().sum()

print("Postulaciones duplicadas:", duplicados_app)

Postulaciones duplicadas: 0


Ahora revisemos los valores nulos

In [188]:
# Cantidad de valores nulos por columna

nulos = applications_jobs_companies.isna().sum()

print(nulos)

_id_application                 0
job                             0
createdAt_application           1
applicationStatus             152
_id_job                         5
companyId                       5
title                           5
department                     15
modality                        5
publishUntil                    5
status                          5
createdAt_job                   5
country                        96
geographicDepartment          119
jobType                        89
verificationStatus            168
isExternalOffer               466
externalCompanyName           467
_id                            26
businessName                  341
industry                      393
verificationStatus_company    153
country_company               341
plan                           27
isActive                       26
createdAt                      26
planType                       26
dtype: int64


print("""
| Columna                     | Nulos | Interpretación                              |
|-----------------------------|-------|---------------------------------------------|
| _id                         | 26    | 26 no tienen empresa relacionada            |
| businessName                | 341   | 341 postulaciones sin empresa encontrada    |
| industry                    | 393   | Muchos registros sin industria              |
| verificationStatus_company  | 153   | Faltan datos de verificación                |
| country_company             | 341   | Coincide con las empresas no encontradas    |
| plan                        | 27    | Casi todas tienen plan                      |
| isActive                    | 26    | 26 sin empresa                              |
| createdAt                   | 26    | 26 sin empresa                              |
| planType                    | 26    | 26 sin empresa                              |
""")

Durante la validación del cruce se identificaron valores faltantes en los atributos de empresa. Estos fueron conservados debido a que representan registros sin correspondencia entre las colecciones y constituyen información relevante para evaluar la integridad de las relaciones.

In [189]:
applications_jobs_companies['country'].value_counts(dropna=False)

,count
country,
Perú,371
NaN,96


In [190]:
applications_jobs_companies['modality'].value_counts(dropna=False)

,count
modality,
presencial,314
híbrido,101
remoto,47
NaN,5


In [191]:
applications_jobs_companies['jobType'].value_counts(dropna=False)

,count
jobType,
SENIOR,173
JUNIOR,113
NaN,89
TRAINEE,51
PRACTICE,21
INTERNSHIP,20


In [192]:
applications_jobs_companies['applicationStatus'].value_counts(dropna=False)

,count
applicationStatus,
ENVIADO,209
NaN,152
EN_REVISION,64
SELECCIONADO,25
DESCARTADO,12
RETIRADO,4
ENTREVISTA,1


In [193]:
tabla_jobtype = (
    applications_jobs_companies['jobType']
    .value_counts(dropna=False)
    .reset_index()
)

tabla_jobtype.columns = ['jobType', 'Cantidad']

tabla_jobtype

,jobType,Cantidad
0,SENIOR,173
1,JUNIOR,113
2,NaN,89
3,TRAINEE,51
4,PRACTICE,21
5,INTERNSHIP,20


In [194]:
tabla_country = (
    applications_jobs_companies['country']
    .value_counts(dropna=False)
    .reset_index()
)

tabla_country.columns = ['country', 'Cantidad']

tabla_country

,country,Cantidad
0,Perú,371
1,NaN,96


In [195]:
tabla_modality = (
    applications_jobs_companies['modality']
    .value_counts(dropna=False)
    .reset_index()
)

tabla_modality.columns = ['modality', 'Cantidad']

tabla_modality

,modality,Cantidad
0,presencial,314
1,híbrido,101
2,remoto,47
3,NaN,5


In [196]:
tabla_status = (
    applications_jobs_companies['applicationStatus']
    .value_counts(dropna=False)
    .reset_index()
)

tabla_status.columns = ['applicationStatus', 'Cantidad']

tabla_status

,applicationStatus,Cantidad
0,ENVIADO,209
1,NaN,152
2,EN_REVISION,64
3,SELECCIONADO,25
4,DESCARTADO,12
5,RETIRADO,4
6,ENTREVISTA,1


In [197]:
tabla_department = (
    applications_jobs_companies['department']
    .value_counts(dropna=False)
    .reset_index()
)

tabla_department.columns = ['department', 'Cantidad']

tabla_department

,department,Cantidad
0,"Marketing, Publicidad",151
1,Área de Marketing,43
2,Ventas/Comercial,42
3,"Audiovisual, Marketing y Ventas",29
4,Comercial,19
5,Gerencia,19
6,Commercial Squad,18
7,Marketing / Contenido,17
8,Proyectos,17
9,NaN,15


In [198]:
tabla_geo = (
    applications_jobs_companies['geographicDepartment']
    .value_counts(dropna=False)
    .reset_index()
)

tabla_geo.columns = ['geographicDepartment', 'Cantidad']

tabla_geo

,geographicDepartment,Cantidad
0,Lima,343
1,<NA>,119
2,Amazonas,3
3,Áncash,2


In [199]:
applications_jobs_companies['country'].value_counts(dropna=False)

,count
country,
Perú,371
NaN,96


In [200]:
applications_jobs_companies['modality'].value_counts(dropna=False)

,count
modality,
presencial,314
híbrido,101
remoto,47
NaN,5


In [201]:
applications_jobs_companies['applicationStatus'].value_counts(dropna=False)

,count
applicationStatus,
ENVIADO,209
NaN,152
EN_REVISION,64
SELECCIONADO,25
DESCARTADO,12
RETIRADO,4
ENTREVISTA,1


In [202]:
tabla_country = (
    applications_jobs_companies['country']
    .value_counts(dropna=False)
    .reset_index()
)

tabla_country.columns = ['country', 'Cantidad']

tabla_modality = (
    applications_jobs_companies['modality']
    .value_counts(dropna=False)
    .reset_index()
)

tabla_modality.columns = ['modality', 'Cantidad']

tabla_status = (
    applications_jobs_companies['applicationStatus']
    .value_counts(dropna=False)
    .reset_index()
)

tabla_status.columns = ['applicationStatus', 'Cantidad']

print("=== COUNTRY ===")
display(tabla_country)

print("=== MODALITY ===")
display(tabla_modality)

print("=== APPLICATION STATUS ===")
display(tabla_status)

=== COUNTRY ===


,country,Cantidad
0,Perú,371
1,NaN,96


=== MODALITY ===


,modality,Cantidad
0,presencial,314
1,híbrido,101
2,remoto,47
3,NaN,5


=== APPLICATION STATUS ===


,applicationStatus,Cantidad
0,ENVIADO,209
1,NaN,152
2,EN_REVISION,64
3,SELECCIONADO,25
4,DESCARTADO,12
5,RETIRADO,4
6,ENTREVISTA,1


In [203]:
print("=== VALIDACIÓN FINAL ===")

print("Filas:", applications_jobs_companies.shape[0])

print("\nDuplicados de postulación:")
print(applications_jobs_companies['_id_application'].duplicated().sum())

print("\nNulos en variables categóricas:")
print(
    applications_jobs_companies[
        ['country', 'modality', 'applicationStatus']
    ].isna().sum()
)

print("\nCountry:")
print(applications_jobs_companies['country'].value_counts(dropna=False))

print("\nModality:")
print(applications_jobs_companies['modality'].value_counts(dropna=False))

print("\nApplication Status:")
print(applications_jobs_companies['applicationStatus'].value_counts(dropna=False))

=== VALIDACIÓN FINAL ===
Filas: 467

Duplicados de postulación:
0

Nulos en variables categóricas:
country               96
modality               5
applicationStatus    152
dtype: int64

Country:
country
Perú    371
NaN      96
Name: count, dtype: int64

Modality:
modality
presencial    314
híbrido       101
remoto         47
NaN             5
Name: count, dtype: int64

Application Status:
applicationStatus
ENVIADO         209
NaN             152
EN_REVISION      64
SELECCIONADO     25
DESCARTADO       12
RETIRADO          4
ENTREVISTA        1
Name: count, dtype: int64


Primero hacemos una copia del DataFrame que ya validamos:

In [204]:
applications_final = applications_jobs_companies.copy()

print("Filas:", applications_final.shape[0])
print("Columnas:", applications_final.shape[1])

Filas: 467
Columnas: 27


Paso 2 — Revisar las 27 columnas

In [205]:
applications_final = applications_jobs_companies.copy()

print("Filas:", applications_final.shape[0])
print("Columnas:", applications_final.shape[1])

print("\nColumnas:")
print(applications_final.columns.tolist())

Filas: 467
Columnas: 27

Columnas:
['_id_application', 'job', 'createdAt_application', 'applicationStatus', '_id_job', 'companyId', 'title', 'department', 'modality', 'publishUntil', 'status', 'createdAt_job', 'country', 'geographicDepartment', 'jobType', 'verificationStatus', 'isExternalOffer', 'externalCompanyName', '_id', 'businessName', 'industry', 'verificationStatus_company', 'country_company', 'plan', 'isActive', 'createdAt', 'planType']


In [206]:
applications_jobs_companies['applicationStatus'].value_counts(dropna=False)

,count
applicationStatus,
ENVIADO,209
NaN,152
EN_REVISION,64
SELECCIONADO,25
DESCARTADO,12
RETIRADO,4
ENTREVISTA,1


In [207]:
applications_final['_id_application'].duplicated().sum()

np.int64(0)

In [208]:
applications_final.isnull().sum()

,0
_id_application,0
job,0
createdAt_application,1
applicationStatus,152
_id_job,5
companyId,5
title,5
department,15
modality,5
publishUntil,5


In [209]:
applications_final[['createdAt', 'createdAt_job']].dtypes

,0
createdAt,datetime64[ns]
createdAt_job,datetime64[ns]


In [210]:
# ==========================================
# REVISIÓN: OFERTAS EXTERNAS
# ==========================================

jobs_clean[['isExternalOffer', 'externalCompanyName']].value_counts(dropna=False)

isExternalOffer  externalCompanyName             
NaN              NaN                                 53
True             Caja Arequipa                       23
                 CAJA TRUJILLO                       19
                 Bitel                               17
                 ManpowerGroup Perú                  14
                                                     ..
                 Visiva                               1
                 Vivoo                                1
                 WS Business Service Group S.A.C.     1
                 Wanchaq, Cusco                       1
                 ACCIONA                              1
Name: count, Length: 682, dtype: int64

In [211]:
# ==========================================
# REVISIÓN: INFORMACIÓN DE OFERTAS EXTERNAS
# ==========================================

print("Ofertas externas:", jobs_clean['isExternalOffer'].eq(True).sum())
print("Empresas externas identificadas:", jobs_clean['externalCompanyName'].notna().sum())
print("Empleos sin empresa externa:", jobs_clean['externalCompanyName'].isna().sum())

Ofertas externas: 1044
Empresas externas identificadas: 1044
Empleos sin empresa externa: 58


In [212]:
# ==========================================
# RECONSTRUCCIÓN: APPLICATIONS + JOBS
# ==========================================

applications_jobs = applications_clean.merge(
    jobs_clean,
    left_on='job',
    right_on='_id',
    how='left',
    suffixes=('_application', '_job')
)

print(f"Filas: {applications_jobs.shape[0]}")
print(f"Columnas: {applications_jobs.shape[1]}")

Filas: 467
Columnas: 18


In [213]:
# ==========================================
# RECONSTRUCCIÓN: APPLICATIONS + JOBS + COMPANIES
# ==========================================

applications_final = applications_jobs.merge(
    companies_clean,
    left_on='companyId',
    right_on='_id',
    how='left',
    suffixes=('', '_company')
)

print(f"Filas: {applications_final.shape[0]}")
print(f"Columnas: {applications_final.shape[1]}")

Filas: 467
Columnas: 27


In [214]:
# ==========================================
# VALIDACIÓN DEL DATASET FINAL
# ==========================================

print("Ofertas externas:", applications_final['isExternalOffer'].eq(True).sum())
print("Empresas externas identificadas:", applications_final['externalCompanyName'].notna().sum())

Ofertas externas: 0
Empresas externas identificadas: 0


In [215]:
# ==========================================
# VALIDACIÓN: OFERTAS EXTERNAS EN APPLICATIONS_JOBS
# ==========================================

print("Ofertas externas:", applications_jobs['isExternalOffer'].eq(True).sum())
print("Empresas externas identificadas:", applications_jobs['externalCompanyName'].notna().sum())

Ofertas externas: 0
Empresas externas identificadas: 0


## CREAR Y COMENTAR MÉTRICAS

En esta etapa se elaboran métricas utilizando las colecciones previamente limpiadas y el dataset integrado applications_final. Cada fuente se utiliza según el tipo de información que se desea analizar, permitiendo obtener indicadores sobre las empresas registradas, las ofertas laborales y las postulaciones de la plataforma.

In [216]:
# ==========================================
# KPI 1: TOTAL DE EMPRESAS REGISTRADAS EN LA PLATAFORMA
# ==========================================

total_empresas = companies['_id'].nunique()

print(f"Total de empresas registradas en la plataforma: {total_empresas}")

Total de empresas registradas en la plataforma: 83


**Interpretación:** La plataforma cuenta con 83 empresas registradas en la colección de empresas, correspondientes a organizaciones que cuentan con un registro o perfil dentro de la plataforma.

In [217]:
# ==========================================
# KPI 2: TOTAL DE EMPLEOS REGISTRADOS
# ==========================================

total_empleos = jobs_clean['_id'].nunique()

print(f"Total de empleos registrados: {total_empleos}")

Total de empleos registrados: 1102


**Interpretación:** La plataforma registra un total de 1,096 ofertas laborales. De este total, corresponden a ofertas externas como internas. Este indicador permite conocer el volumen total de oportunidades laborales disponibles en la base analizada.

In [218]:
# ==========================================
# KPI 3: TOTAL DE POSTULACIONES REGISTRADAS
# ==========================================

total_postulaciones = applications_clean['_id'].nunique()

print(f"Total de postulaciones registradas: {total_postulaciones}")

Total de postulaciones registradas: 467


**Interpretación:** La plataforma cuenta con un total de 467 postulaciones registradas. Este indicador representa el número total de postulaciones realizadas por los usuarios y permite conocer el volumen general de interacción de los postulantes con las ofertas laborales.

In [219]:
# ==========================================
# KPI 4: POSTULACIONES POR ESTADO
# ==========================================

postulaciones_estado = applications_clean['applicationStatus'].value_counts(dropna=False)

print(postulaciones_estado)

applicationStatus
ENVIADO         209
NaN             152
EN_REVISION      64
SELECCIONADO     25
DESCARTADO       12
RETIRADO          4
ENTREVISTA        1
Name: count, dtype: int64


**Interpretación:** La mayor cantidad de postulaciones corresponde al estado “ENVIADO”, con 209 registros. Asimismo, se identifican 152 postulaciones sin estado registrado, lo que representa una cantidad significativa de información faltante. Entre las postulaciones con estado informado, 64 se encuentran “EN_REVISION”, 25 están “SELECCIONADO”, 12 “DESCARTADO”, 4 “RETIRADO” y 1 en “ENTREVISTA”.

In [220]:
# ==========================================
# REVISIÓN: POSTULACIONES SIN ESTADO
# ==========================================

sin_estado = applications_clean[
    applications_clean['applicationStatus'].isna()
]

print(f"Postulaciones sin estado: {len(sin_estado)}")

sin_estado.head(10)

Postulaciones sin estado: 152


,_id,job,createdAt,applicationStatus
0,6917cdf4998d66b34dac075b,6917cd88998d66b34dac0734,2025-11-15 00:48:52.932,NaN
1,692867743b4884927933f66e,692797626dc39bf20c52f60f,2025-11-27 15:00:04.307,NaN
2,6928ab6e985136edda36ae82,69279ce46dc39bf20c52f61c,2025-11-27 19:50:06.623,NaN
3,692a2b217f1f3ab5036abc0d,69279ddf6dc39bf20c52f62f,2025-11-28 23:07:13.054,NaN
4,692a5c537f1f3ab5036abe21,69279ce46dc39bf20c52f61c,2025-11-29 02:37:07.991,NaN
5,69308e2b53aa614862331c3b,69279ce46dc39bf20c52f61c,2025-12-03 19:23:23.539,NaN
6,69308e5f53aa614862331c57,69279ddf6dc39bf20c52f62f,2025-12-03 19:24:15.980,NaN
7,693090a753aa614862331d66,69279ce46dc39bf20c52f61c,2025-12-03 19:33:59.344,NaN
8,693090e553aa614862331d90,69279f586dc39bf20c52f64b,2025-12-03 19:35:01.189,NaN
9,6930978d53aa614862331eae,69279ce46dc39bf20c52f61c,2025-12-03 20:03:25.755,NaN


In [221]:
# ==========================================
# KPI 5: OFERTAS EXTERNAS
# ==========================================

ofertas_externas = jobs_clean['isExternalOffer'].eq(True).sum()

print(f"Total de ofertas externas: {ofertas_externas}")

Total de ofertas externas: 1044


**Interpretación:** La plataforma registra 1,038 ofertas laborales identificadas como externas. Este indicador permite conocer la cantidad de oportunidades laborales externas presentes en la base de empleos, diferenciándolas de las demás ofertas registradas.

In [222]:
# ==========================================
# KPI 6: OFERTAS EXTERNAS POR EMPRESA
# ==========================================

ofertas_por_empresa_externa = (
    jobs_clean['externalCompanyName']
    .dropna()
    .value_counts()
)

print(ofertas_por_empresa_externa.head(10))

externalCompanyName
Caja Arequipa                    23
CAJA TRUJILLO                    19
Bitel                            17
ManpowerGroup Perú               14
Importante empresa del sector    13
Danper Trujillo SAC              11
Adecco Perú S.A.                 10
Manpower                          9
Grupo Pacasmayo                   7
KOMATSU - MITSUI MAQUINARIAS      7
Name: count, dtype: int64


In [223]:
# ==========================================
# REVISIÓN: NOMBRES DE EMPRESAS EXTERNAS
# ==========================================

empresas_externas = (
    jobs_clean['externalCompanyName']
    .dropna()
    .value_counts()
)

print(empresas_externas.to_string())

externalCompanyName
Caja Arequipa                                                                                                                                                                                                                                                                23
CAJA TRUJILLO                                                                                                                                                                                                                                                                19
Bitel                                                                                                                                                                                                                                                                        17
ManpowerGroup Perú                                                                                                                                                  

In [224]:
jobs_clean['externalCompanyName'] = jobs_clean['externalCompanyName'].replace({
    'CAJA TRUJILLO': 'Caja Trujillo',
    'Caja Trujillo': 'Caja Trujillo',

    'KOMATSU - MITSUI MAQUINARIAS': 'Komatsu Mitsui',
    'KOMATSU MITSUI': 'Komatsu Mitsui',

    'Universidad Tecnológica del Perú': 'Universidad Tecnológica del Perú',
    'UNIVERSIDAD TECNOLOGICA DEL PERU': 'Universidad Tecnológica del Perú',
    'UNIVERSIDAD TECNOLOGICA DEL PERU(UTP)': 'Universidad Tecnológica del Perú',

    'Repsol': 'Repsol',
    'REPSOL': 'Repsol',

    'Camposol': 'Camposol',
    'CAMPOSOL': 'Camposol',
    'CAMPOSOL S.A.': 'Camposol',

    'EUROFIRMS': 'Eurofirms',
    'Eurofirms Perú': 'Eurofirms',
})

In [225]:
# ==========================================
# REVISIÓN DE TODAS LAS VARIANTES MANPOWER
# ==========================================

manpower = jobs_clean[
    jobs_clean['externalCompanyName']
    .astype(str)
    .str.contains('manpower', case=False, na=False)
]

manpower['externalCompanyName'].value_counts()

,count
externalCompanyName,
ManpowerGroup Perú,14
Manpower,9
MANPOWER RPO BCP,3
MANPOWER PERU S.A.C.,2
Manpower Perú,1
Practicante de tesorería Manpower,1
ManpowerGroup RPO,1


In [226]:
# ==========================================
# ESTANDARIZACIÓN DE MANPOWERGROUP
# ==========================================

manpower_variantes = [
    'ManpowerGroup Perú',
    'Manpower',
    'MANPOWER RPO BCP',
    'MANPOWER PERU S.A.C.',
    'Manpower Perú',
    'ManpowerGroup RPO',
    'Practicante de tesorería Manpower'
]

jobs_clean.loc[
    jobs_clean['externalCompanyName'].isin(manpower_variantes),
    'externalCompanyName'
] = 'ManpowerGroup'

In [227]:
# ==========================================
# VERIFICAR EMPRESAS ESTANDARIZADAS
# ==========================================

empresas_externas = (
    jobs_clean['externalCompanyName']
    .dropna()
    .value_counts()
)

print(empresas_externas.head(30).to_string())

externalCompanyName
ManpowerGroup                           31
Caja Trujillo                           24
Caja Arequipa                           23
Bitel                                   17
Importante empresa del sector           13
Komatsu Mitsui                          12
Danper Trujillo SAC                     11
Adecco Perú S.A.                        10
NTT DATA                                 7
Grupo Pacasmayo                          7
Universidad Tecnológica del Perú         7
Banco de Crédito del Perú                6
Camposol                                 6
Caja Ica                                 6
Eurofirms                                5
Grupo Mannucci                           5
Grupo Gloria                             5
Repsol                                   5
Grupo Tawa                               5
Empresa Confidencial                     5
Nexa Resources                           4
Grupo La Joya                            4
LOGISTONE S.A.C.                  

In [228]:
# ==========================================
# ESTANDARIZACIÓN FINAL DE EMPRESAS
# ==========================================

estandarizacion_empresas = {
    # Gloria
    'Gloria': 'Grupo Gloria',

    # Repsol
    'REPSOL': 'Repsol',

    # Camposol
    'CAMPOSOL': 'Camposol',
    'CAMPOSOL S.A.': 'Camposol',

    # Eurofirms
    'EUROFIRMS': 'Eurofirms',

    # Cetemin
    'Cetemin': 'CETEMIN',

    # Caja Cusco
    'CAJA CUSCO': 'Caja Cusco',

    # Cartavio
    'Cartavio Rum Company': 'CARTAVIO RUM COMPANY S.A.C.',

    # Topitop
    'Topitop': 'Topi Top',

    # Indra
    'INDRA PERU': 'Indra',

    # Minera Bateas
    'MINERA BATEAS': 'Minera Bateas',

    # Coopac Kori
    'Coopac Kori': 'COOPAC KORI',

    # Transportes Cruz del Sur
    'Transportes Cruz Del Sur S.A.C': 'Transportes Cruz Del Sur S.A.C.',

    # Tisur
    'Tisur': 'Tisur S.A.',

    # Natura
    'Natura Lima Metropolitan Area': 'Natura',

    # Expertia
    'Expertia Travel Lima': 'Expertia Travel',

    # Overall Strategy
    'OVERALL STRATEGY S.A.C': 'Overall Strategy',

    # PROSERING
    'PROSERING SRLTDA': 'PROSERING',
    'PROSERING Arequipa': 'PROSERING',

    # Grupo Centenario
    'Grupo Centenario Lima': 'Grupo Centenario',

    # Grupo Aenza
    'Grupo Aenza': 'AENZA',

    # Backus
    'BACKUS': 'Backus',
}

jobs_clean['externalCompanyName'] = (
    jobs_clean['externalCompanyName']
    .replace(estandarizacion_empresas)
)

In [229]:
estandarizacion_empresas = {
    # Empresas no identificadas
    'Importante empresa del sector': 'Importante Empresa en el sector',
    'Importante Empresa en el sector': 'Importante Empresa en el sector',
    'Importante del Sector': 'Importante Empresa en el sector',
    'Importante': 'Importante Empresa en el sector',
    'Empresa importante en el sector': 'Importante Empresa en el sector',
    'Empresa Confidencial': 'Importante Empresa en el sector',
    'Confidencial': 'Importante Empresa en el sector',

    # Gloria
    'Gloria': 'Grupo Gloria',
    'Gloria S.A': 'Grupo Gloria',
    'Gloria S.A.': 'Grupo Gloria',

    # Komatsu Mitsui
    'KOMATSU - MITSUI MAQUINARIAS': 'Komatsu Mitsui',
    'KOMATSU MITSUI': 'Komatsu Mitsui',

    # Caja Trujillo
    'CAJA TRUJILLO': 'Caja Trujillo',

    # Repsol
    'REPSOL': 'Repsol',

    # Camposol
    'CAMPOSOL': 'Camposol',
    'CAMPOSOL S.A.': 'Camposol',

    # Eurofirms
    'EUROFIRMS': 'Eurofirms',
    'Eurofirms Perú': 'Eurofirms',

    # UTP
    'UNIVERSIDAD TECNOLOGICA DEL PERU': 'Universidad Tecnológica del Perú',
    'UNIVERSIDAD TECNOLOGICA DEL PERU(UTP)': 'Universidad Tecnológica del Perú',

    # Caja Cusco
    'CAJA CUSCO': 'Caja Cusco',

    # Cartavio
    'Cartavio Rum Company': 'CARTAVIO RUM COMPANY S.A.C.',

    # Adecco
    'Adecco Perú': 'Adecco Perú S.A.',
    'Adecco Perú S.A.SAC': 'Adecco Perú S.A.',

    # Tisur
    'Tisur': 'Tisur S.A.',

    # Cetemin
    'Cetemin': 'CETEMIN',

    # Manpower
    'Manpower': 'ManpowerGroup',
    'ManpowerGroup Perú': 'ManpowerGroup',
    'MANPOWER PERU S.A.C.': 'ManpowerGroup',
    'Manpower Perú': 'ManpowerGroup',
    'MANPOWER RPO BCP': 'ManpowerGroup',
    'ManpowerGroup RPO': 'ManpowerGroup',
    'Practicante de tesorería Manpower': 'ManpowerGroup',

    # Danper
    'Dirigido a hombres y mujeres Danper Trujillo SAC': 'Danper Trujillo SAC',

    # Grupo Centenario
    'Grupo Centenario Lima': 'Grupo Centenario',

    # Aenza
    'Grupo Aenza': 'AENZA',

    # Prosering
    'PROSERING SRLTDA': 'PROSERING',
    'PROSERING Arequipa': 'PROSERING',

    # Natura
    'Natura Lima Metropolitan Area': 'Natura',

    # Expertia
    'Expertia Travel Lima': 'Expertia Travel',

    # Overall Strategy
    'OVERALL STRATEGY S.A.C': 'Overall Strategy',

    # Topitop
    'Topitop': 'Topi Top',

    # Backus
    'BACKUS': 'Backus',

    # Transportes Cruz del Sur
    'Transportes Cruz Del Sur S.A.C': 'Transportes Cruz Del Sur S.A.C.',
}

In [230]:
jobs_clean['externalCompanyName'] = (
    jobs_clean['externalCompanyName']
    .replace(estandarizacion_empresas)
)

In [231]:
# Verificar cómo quedaron las empresas después de la estandarización

ranking_empresas = (
    jobs_clean['externalCompanyName']
    .value_counts()
    .reset_index()
)

ranking_empresas.columns = ['externalCompanyName', 'total_empleos']

ranking_empresas.head(20)

,externalCompanyName,total_empleos
0,ManpowerGroup,31
1,Importante Empresa en el sector,28
2,Caja Trujillo,24
3,Caja Arequipa,23
4,Bitel,17
5,Danper Trujillo SAC,12
6,Adecco Perú S.A.,12
7,Komatsu Mitsui,12
8,Grupo Gloria,10
9,Grupo Pacasmayo,7


In [232]:
jobs_clean[
    jobs_clean['externalCompanyName'].str.contains(
        'Adecco',
        case=False,
        na=False
    )
]['externalCompanyName'].value_counts()

,count
externalCompanyName,
Adecco Perú S.A.,12
ADECCO BCP,1
Practicante Profesional de Contabilidad Adecco Perú S.A.,1


In [233]:
# Estandarizar las variantes de Adecco
estandarizacion_empresas.update({
    'ADECCO BCP': 'Adecco Perú S.A.',
    'Practicante Profesional de Contabilidad Adecco Perú S.A.': 'Adecco Perú S.A.'
})

# Aplicar la estandarización
jobs_clean['externalCompanyName'] = (
    jobs_clean['externalCompanyName']
    .replace(estandarizacion_empresas)
)

# Verificar el resultado
jobs_clean[
    jobs_clean['externalCompanyName'].str.contains(
        'Adecco',
        case=False,
        na=False
    )
]['externalCompanyName'].value_counts()

,count
externalCompanyName,
Adecco Perú S.A.,14


In [234]:
ranking_empresas = (
    jobs_clean['externalCompanyName']
    .value_counts()
    .reset_index()
)

ranking_empresas.columns = ['Empresa', 'Total_empleos']

ranking_empresas

,Empresa,Total_empleos
0,ManpowerGroup,31
1,Importante Empresa en el sector,28
2,Caja Trujillo,24
3,Caja Arequipa,23
4,Bitel,17
...,...,...
631,ALS,1
632,AHP HEADHUNTING,1
633,SERVICIOS LOGISTICOS,1
634,Consejeros & Corredores de Seguros S.A.,1


In [235]:
# Aplicar TODA la estandarización al campo de empresas
jobs_clean['externalCompanyName'] = (
    jobs_clean['externalCompanyName']
    .replace(estandarizacion_empresas)
)

In [236]:
# Contar empleos por empresa después de estandarizar
empresa_total_empleos = (
    jobs_clean['externalCompanyName']
    .value_counts()
    .reset_index()
)

empresa_total_empleos.columns = [
    'externalCompanyName',
    'total_empleos'
]

empresa_total_empleos

,externalCompanyName,total_empleos
0,ManpowerGroup,31
1,Importante Empresa en el sector,28
2,Caja Trujillo,24
3,Caja Arequipa,23
4,Bitel,17
...,...,...
631,ALS,1
632,AHP HEADHUNTING,1
633,SERVICIOS LOGISTICOS,1
634,Consejeros & Corredores de Seguros S.A.,1


In [237]:
estandarizacion_empresas = {

    # =========================================================
    # EMPRESAS NO IDENTIFICADAS
    # =========================================================
    'Importante empresa del sector': 'Importante Empresa en el sector',
    'Importante Empresa en el sector': 'Importante Empresa en el sector',
    'Importante del Sector': 'Importante Empresa en el sector',
    'Importante': 'Importante Empresa en el sector',
    'Empresa importante en el sector': 'Importante Empresa en el sector',
    'Empresa Confidencial': 'Importante Empresa en el sector',
    'Confidencial': 'Importante Empresa en el sector',


    # =========================================================
    # GLORIA
    # =========================================================
    'Gloria': 'Grupo Gloria',
    'Gloria S.A': 'Grupo Gloria',
    'Gloria S.A.': 'Grupo Gloria',


    # =========================================================
    # KOMATSU MITSUI
    # =========================================================
    'KOMATSU - MITSUI MAQUINARIAS': 'Komatsu Mitsui',
    'KOMATSU MITSUI': 'Komatsu Mitsui',


    # =========================================================
    # CAJA TRUJILLO
    # =========================================================
    'CAJA TRUJILLO': 'Caja Trujillo',


    # =========================================================
    # REPSOL
    # =========================================================
    'REPSOL': 'Repsol',


    # =========================================================
    # CAMPOSOL
    # =========================================================
    'CAMPOSOL': 'Camposol',
    'CAMPOSOL S.A.': 'Camposol',


    # =========================================================
    # EUROFIRMS
    # =========================================================
    'EUROFIRMS': 'Eurofirms',
    'Eurofirms Perú': 'Eurofirms',


    # =========================================================
    # UTP
    # =========================================================
    'UNIVERSIDAD TECNOLOGICA DEL PERU':
        'Universidad Tecnológica del Perú',

    'UNIVERSIDAD TECNOLOGICA DEL PERU(UTP)':
        'Universidad Tecnológica del Perú',


    # =========================================================
    # CAJA CUSCO
    # =========================================================
    'CAJA CUSCO': 'Caja Cusco',


    # =========================================================
    # CARTAVIO
    # =========================================================
    'Cartavio Rum Company':
        'CARTAVIO RUM COMPANY S.A.C.',


    # =========================================================
    # ADECCO
    # =========================================================
    'Adecco Perú':
        'Adecco Perú S.A.',

    'Adecco Perú S.A.SAC':
        'Adecco Perú S.A.',

    'ADECCO BCP':
        'Adecco Perú S.A.',

    'Practicante Profesional de Contabilidad Adecco Perú S.A.':
        'Adecco Perú S.A.',


    # =========================================================
    # TISUR
    # =========================================================
    'Tisur': 'Tisur S.A.',


    # =========================================================
    # CETEMIN
    # =========================================================
    'Cetemin': 'CETEMIN',


    # =========================================================
    # MANPOWER
    # =========================================================
    'Manpower': 'ManpowerGroup',
    'ManpowerGroup Perú': 'ManpowerGroup',
    'MANPOWER PERU S.A.C.': 'ManpowerGroup',
    'Manpower Perú': 'ManpowerGroup',
    'MANPOWER RPO BCP': 'ManpowerGroup',
    'ManpowerGroup RPO': 'ManpowerGroup',
    'Practicante de tesorería Manpower': 'ManpowerGroup',


    # =========================================================
    # DANPER
    # =========================================================
    'Dirigido a hombres y mujeres Danper Trujillo SAC':
        'Danper Trujillo SAC',


    # =========================================================
    # GRUPO CENTENARIO
    # =========================================================
    'Grupo Centenario Lima':
        'Grupo Centenario',


    # =========================================================
    # AENZA
    # =========================================================
    'Grupo Aenza': 'AENZA',


    # =========================================================
    # PROSERING
    # =========================================================
    'PROSERING SRLTDA': 'PROSERING',
    'PROSERING Arequipa': 'PROSERING',


    # =========================================================
    # NATURA
    # =========================================================
    'Natura Lima Metropolitan Area': 'Natura',


    # =========================================================
    # EXPERTIA
    # =========================================================
    'Expertia Travel Lima': 'Expertia Travel',


    # =========================================================
    # OVERALL STRATEGY
    # =========================================================
    'OVERALL STRATEGY S.A.C': 'Overall Strategy',


    # =========================================================
    # TOPITOP
    # =========================================================
    'Topitop': 'Topi Top',


    # =========================================================
    # BACKUS
    # =========================================================
    'BACKUS': 'Backus',


    # =========================================================
    # TRANSPORTES CRUZ DEL SUR
    # =========================================================
    'Transportes Cruz Del Sur S.A.C':
        'Transportes Cruz Del Sur S.A.C.',


    # =========================================================
    # PACÍFICO EPS
    # Solo se agrupan las variantes de Pacífico EPS
    # Pacífico Seguros se mantiene separado
    # =========================================================
    'Pacifico Eps': 'Pacífico EPS',
    'Pacífico EPS': 'Pacífico EPS',


    # =========================================================
    # RANSA
    # =========================================================
    'RANSA COMERCIAL S.A.C':
        'Ransa Comercial S.A.C.',

    'Ransa Comercial S.A.':
        'Ransa Comercial S.A.C.',


    # =========================================================
    # YURA
    # =========================================================
    'Yura S.A':
        'Yura S.A.',


    # =========================================================
    # MIND GROUP
    # =========================================================
    'Mind Group Arequipa':
        'Mind Group',


    # =========================================================
    # NEXUS SALUD OCUPACIONAL
    # =========================================================
    'Nexus Salud Ocupacional Arequipa, Arequipa, Perú':
        'Nexus Salud Ocupacional',


    # =========================================================
    # CLUB INTERNACIONAL AREQUIPA
    # =========================================================
    'Club Internacional Arequipa Arequipa':
        'Club Internacional Arequipa',


    # =========================================================
    # INDRA
    # =========================================================
    'Indra Group':
        'Indra',


    # =========================================================
    # FINANCIERA CONFIANZA
    # =========================================================
    'FINANCIERA CONFIANZA':
        'Financiera Confianza',


    # =========================================================
    # SHOUGANG
    # =========================================================
    'SHOUGANG HIERRO PERU S.A.A':
        'SHOUGANG HIERRO PERU S.A.A.',


    # =========================================================
    # COMPAÑÍA MINERA SOL DE LOS ANDES
    # =========================================================
    'Compañía Minera Sol de los Andes':
        'Compañía Minera Sol de los Andes S.A.C.',


    # =========================================================
    # DIAR INGENIEROS
    # =========================================================
    'DIAR INGENIEROS S.A':
        'Diar Ingenieros S.A.',

    'Diar Ingenieros S. A.':
        'Diar Ingenieros S.A.',


    # =========================================================
    # TIENDAS TAMBO
    # =========================================================
    'TIENDAS TAMBO':
        'Tiendas Tambo',


    # =========================================================
    # INGENIERÍA SUMINISTROS Y SOLUCIONES
    # =========================================================
    '8A INGENIERIA SUMINISTROS Y SOLUCIONES':
        'Ingeniería Suministros y Soluciones'
}

In [238]:
jobs_clean['externalCompanyName'] = (
    jobs_clean['externalCompanyName']
    .replace(estandarizacion_empresas)
)

In [239]:
empresa_total_empleos = (
    jobs_clean['externalCompanyName']
    .value_counts()
    .reset_index()
)

empresa_total_empleos.columns = [
    'externalCompanyName',
    'total_empleos'
]

empresa_total_empleos

,externalCompanyName,total_empleos
0,ManpowerGroup,31
1,Importante Empresa en el sector,28
2,Caja Trujillo,24
3,Caja Arequipa,23
4,Bitel,17
...,...,...
620,Bureau Veritas del Peru SA,1
621,MEXICHEM PERÚ S.A.,1
622,Cencosud Perú S.A.,1
623,CRP Radios,1


In [240]:
!pip install rapidfuzz

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.1/3.1 MB 41.9 MB/s eta 0:00:00


In [241]:
from rapidfuzz import process, fuzz
import pandas as pd

# Obtener nombres únicos de empresas
nombres = (
    jobs_clean['externalCompanyName']
    .dropna()
    .unique()
    .tolist()
)

# Buscar posibles nombres similares
resultados = []

for nombre in nombres:
    similares = process.extract(
        nombre,
        nombres,
        scorer=fuzz.token_sort_ratio,
        limit=5
    )

    for parecido, puntuacion, _ in similares:

        # No compararse consigo mismo
        if nombre == parecido:
            continue

        # Mostrar solo coincidencias bastante similares
        if puntuacion >= 80:
            resultados.append([
                nombre,
                parecido,
                puntuacion
            ])

# Crear tabla
posibles_duplicados = pd.DataFrame(
    resultados,
    columns=[
        'nombre_1',
        'nombre_2',
        'similitud'
    ]
)

# Evitar repetir A-B y B-A
posibles_duplicados['par'] = posibles_duplicados.apply(
    lambda x: tuple(sorted([x['nombre_1'], x['nombre_2']])),
    axis=1
)

posibles_duplicados = (
    posibles_duplicados
    .drop_duplicates('par')
    .drop(columns='par')
    .sort_values('similitud', ascending=False)
)

posibles_duplicados.head(100)

,nombre_1,nombre_2,similitud
6,Industrias San Miguel!,Industrias San Miguel,97.674419
2,ALS LS PERU S.A.C.,CALL PERU S.A.C.,88.235294
1,Universidad Norbert Wiener,Universidad Privada Norbert Wiener,86.666667
0,Izipay,izipay,83.333333
5,Llankay Consultores,Khana Consultores,83.333333


In [242]:
estandarizacion_empresas.update({
    'Universidad Norbert Wiener': 'Universidad Privada Norbert Wiener'
})

In [243]:
jobs_clean['externalCompanyName'] = (
    jobs_clean['externalCompanyName']
    .replace(estandarizacion_empresas)
)

In [244]:
jobs_clean[
    jobs_clean['externalCompanyName'].str.contains(
        'Wiener',
        case=False,
        na=False
    )
]['externalCompanyName'].value_counts()

,count
externalCompanyName,
Universidad Privada Norbert Wiener,2


In [245]:
# ==========================================
# KPI 7: OFERTAS POR MODALIDAD
# ==========================================

ofertas_por_modalidad = (
    jobs_clean['modality']
    .dropna()
    .value_counts()
)

print(ofertas_por_modalidad)

modality
presencial    952
híbrido        83
remoto         67
Name: count, dtype: int64


**Interpretación:** El mercado laboral analizado presenta una clara preferencia por la modalidad presencial, mientras que las alternativas híbrida y remota representan una proporción menor de las ofertas disponibles.

In [246]:
# ==========================================
# KPI 8: OFERTAS LABORALES PUBLICADAS POR EMPRESA
# ==========================================

mapa_empresas = companies.set_index('_id')['businessName']

ofertas_por_empresa = pd.concat([
    jobs_clean.loc[
        jobs_clean['isExternalOffer'].eq(True),
        'externalCompanyName'
    ],
    jobs_clean.loc[
        jobs_clean['isExternalOffer'].eq(False),
        'companyId'
    ].map(mapa_empresas)
]).dropna().value_counts()

print(ofertas_por_empresa.head(10))

ManpowerGroup                      31
Importante Empresa en el sector    28
Caja Trujillo                      24
Caja Arequipa                      23
Bitel                              17
Adecco Perú S.A.                   14
Komatsu Mitsui                     12
Danper Trujillo SAC                12
Grupo Gloria                       10
Grupo Pacasmayo                     7
Name: count, dtype: int64


**Interpretación:** Se presenta un ranking de las empresas con mayor cantidad de ofertas laborales registradas en la plataforma.

In [247]:
# ==========================================
# KPI 9: OFERTAS PUBLICADAS POR MES
# ==========================================

ofertas_por_mes = (
    jobs_clean
    .assign(mes=jobs_clean['createdAt'].dt.to_period('M'))
    ['mes']
    .value_counts()
    .sort_index()
)

print(ofertas_por_mes)

mes
2025-11      5
2025-12     12
2026-01     10
2026-02      9
2026-03      4
2026-04      6
2026-05      5
2026-06      9
2026-07    829
2026-08    213
Freq: M, Name: count, dtype: int64


In [248]:
print("Fecha mínima:", jobs_clean['createdAt'].min())
print("Fecha máxima:", jobs_clean['createdAt'].max())

Fecha mínima: 2025-11-10 16:55:55.029000
Fecha máxima: 2026-08-10 12:10:22.446000


**Interpretación:** Se presenta la evolución mensual de las ofertas laborales registradas en la plataforma, utilizando la variable createdAt como fecha de creación de la oferta. El periodo analizado comprende desde el 10 de noviembre de 2025 hasta el 7 de agosto de 2026. Se observa un incremento significativo en julio de 2026, con 829 ofertas registradas, seguido de agosto con 207 ofertas hasta la fecha máxima disponible en el dataset.

In [249]:
# ==========================================
# KPI 10: OFERTAS POR DEPARTAMENTO
# ==========================================

ofertas_por_departamento = (
    jobs_clean['geographicDepartment']
    .dropna()
    .value_counts()
)

print(ofertas_por_departamento)

geographicDepartment
Lima           440
Arequipa       246
La Libertad    214
Ica             73
Callao          20
Piura           14
Lambayeque      11
Áncash          10
Cusco            9
Junín            9
Puno             7
Cajamarca        5
Apurímac         3
Ayacucho         2
Moquegua         2
Amazonas         1
Name: count, dtype: Int64


In [250]:
print(
    "Ofertas sin departamento:",
    jobs_clean['geographicDepartment'].isna().sum()
)

Ofertas sin departamento: 36


**Interpretación:** Se presenta la distribución de las ofertas laborales según el departamento registrado. Lima concentra la mayor cantidad de ofertas, con 434 registros, seguida de Arequipa con 246 y La Libertad con 214. Esto evidencia una mayor concentración de oportunidades laborales en estos departamentos. Asimismo, se identificaron 36 ofertas sin departamento registrado, por lo que estas no fueron consideradas en la distribución geográfica.

In [251]:
# ==========================================
# KPI 11: OFERTAS POR NIVEL DEL PUESTO
# ==========================================

ofertas_por_nivel = (
    jobs_clean['jobType']
    .dropna()
    .value_counts()
)

print(ofertas_por_nivel)

jobType
INTERNSHIP    413
PRACTICE       81
JUNIOR         73
TRAINEE        40
SENIOR         23
Name: count, dtype: int64


In [252]:
print(
    "Ofertas sin nivel de puesto:",
    jobs_clean['jobType'].isna().sum()
)

Ofertas sin nivel de puesto: 472


**Interpretación:** Una parte importante de las oportunidades laborales de la plataforma está dirigida a estudiantes y personas que buscan adquirir sus primeras experiencias profesionales, mientras que las ofertas para perfiles SENIOR presentan una menor cantidad. Sin embargo, 472 ofertas no tienen información registrada en el campo jobType, por lo que estos resultados representan únicamente las ofertas que cuentan con este dato.

In [253]:
# ==========================================
# REVISIÓN COMPLETA DE jobType
# ==========================================

print("Valores nulos:")
print(jobs_clean['jobType'].isna().sum())

print("\nValores vacíos:")
print((jobs_clean['jobType'].astype('string').str.strip() == '').sum())

print("\nValores registrados:")
print(jobs_clean['jobType'].value_counts(dropna=False))

Valores nulos:
472

Valores vacíos:
0

Valores registrados:
jobType
NaN           472
INTERNSHIP    413
PRACTICE       81
JUNIOR         73
TRAINEE        40
SENIOR         23
Name: count, dtype: int64


**Interpretación general :**
En general, el análisis muestra que Laboral.ai cuenta con una cantidad importante de oportunidades laborales, principalmente externas y de modalidad presencial. Las ofertas se concentran principalmente en Lima, Arequipa y La Libertad, y se observa un fuerte crecimiento en las publicaciones durante julio de 2026. Además, existe una alta presencia de ofertas de pasantías (INTERNSHIP), lo que indica que la plataforma tiene una importante orientación hacia estudiantes y personas que buscan iniciar su experiencia laboral. En conjunto, los KPI permiten conocer qué tipo de oportunidades ofrece la plataforma, dónde se concentran y qué perfiles son los más solicitados.

## CREAR Y COMENTAR GRÁFICOS

In [254]:
# ==========================================
# GRÁFICO 1: POSTULACIONES POR ESTADO
# (Gráfico de barras interactivo)
# ==========================================

import plotly.express as px

postulaciones_estado_grafico = (
    applications_clean['applicationStatus']
    .fillna('SIN ESTADO')
    .value_counts()
    .reset_index()
)

postulaciones_estado_grafico.columns = ['Estado', 'Cantidad']

fig = px.bar(
    postulaciones_estado_grafico,
    x='Estado',
    y='Cantidad',
    title='Postulaciones por estado',
    labels={
        'Estado': 'Estado de la postulación',
        'Cantidad': 'Número de postulaciones'
    },
    text='Cantidad'
)

fig.update_traces(
    marker_color='#0a99ac',
    textposition='outside'
)

fig.update_layout(
    xaxis_title='Estado de la postulación',
    yaxis_title='Número de postulaciones',
    hovermode='x unified'
)

fig.show()

La mayor cantidad de postulaciones se encuentra en estado ENVIADO, con 209 registros, seguida de 64 postulaciones EN_REVISION y 25 SELECCIONADO. Además, se identifican 152 postulaciones sin estado registrado, lo que representa una cantidad importante de información faltante.

In [255]:
# ==========================================
# GRÁFICO 2: OFERTAS POR MODALIDAD
# (Gráfico de dona interactivo)
# ==========================================

import plotly.express as px

ofertas_modalidad_grafico = (
    jobs_clean['modality']
    .dropna()
    .value_counts()
    .reset_index()
)

ofertas_modalidad_grafico.columns = ['Modalidad', 'Cantidad']

fig = px.pie(
    ofertas_modalidad_grafico,
    names='Modalidad',
    values='Cantidad',
    title='Distribución de ofertas laborales por modalidad',
    hole=0.45,
    color_discrete_sequence=[
        '#0a99ac',
        '#087f8f',
        '#66c7d1'
    ]
)

fig.update_traces(
    textinfo='label+percent',
    hovertemplate='<b>%{label}</b><br>Ofertas: %{value}<br>Porcentaje: %{percent}<extra></extra>'
)

fig.show()

Las ofertas laborales se concentran principalmente en la modalidad presencial, con 946 registros. En comparación, las modalidades híbrida, con 83 ofertas, y remota, con 67, presentan una participación menor. Esto muestra una clara predominancia del trabajo presencial en las ofertas analizadas.

In [256]:
# ==========================================
# GRÁFICO 3: RANKING DE EMPRESAS POR OFERTAS
# (Gráfico de barras horizontales interactivo)
# ==========================================

ranking_empresas_grafico = (
    ofertas_por_empresa
    .head(10)
    .sort_values(ascending=True)
    .reset_index()
)

ranking_empresas_grafico.columns = ['Empresa', 'Cantidad']

fig = px.bar(
    ranking_empresas_grafico,
    x='Cantidad',
    y='Empresa',
    orientation='h',
    title='Top 10 de empresas con mayor cantidad de ofertas laborales',
    labels={
        'Empresa': 'Empresa',
        'Cantidad': 'Número de ofertas'
    },
    text='Cantidad'
)

fig.update_traces(
    marker_color='#0a99ac',
    textposition='outside'
)

fig.update_layout(
    yaxis={'categoryorder': 'total ascending'}
)

fig.show()

El ranking muestra las empresas con mayor cantidad de ofertas laborales registradas en la plataforma. ManpowerGroup ocupa el primer lugar con 31 ofertas, seguida de Importante Empresa en el sector, con 28, y Caja Trujillo, con 24. Esto permite identificar las empresas con mayor presencia en la publicación de oportunidades laborales.

In [257]:
# ==========================================
# GRÁFICO 4: EVOLUCIÓN DE OFERTAS POR MES
# (Gráfico de líneas interactivo)
# ==========================================

ofertas_mes_grafico = (
    jobs_clean
    .assign(
        mes=jobs_clean['createdAt']
        .dt.to_period('M')
        .astype(str)
    )
    ['mes']
    .value_counts()
    .sort_index()
    .reset_index()
)

ofertas_mes_grafico.columns = ['Mes', 'Cantidad']

fig = px.line(
    ofertas_mes_grafico,
    x='Mes',
    y='Cantidad',
    title='Evolución mensual de las ofertas laborales',
    labels={
        'Mes': 'Mes',
        'Cantidad': 'Número de ofertas'
    },
    markers=True
)

fig.update_traces(
    line_color='#0a99ac',
    marker_color='#0a99ac',
    hovertemplate='Mes: %{x}<br>Ofertas: %{y}<extra></extra>'
)

fig.show()

La evolución mensual muestra un incremento significativo en las publicaciones durante julio de 2026, con 829 ofertas registradas, seguido de agosto con 207 ofertas hasta la fecha disponible en el dataset. Esto evidencia un crecimiento importante en el volumen de publicaciones hacia los últimos meses analizados.

In [258]:
# ==========================================
# GRÁFICO 5: OFERTAS POR DEPARTAMENTO
# (Gráfico de barras horizontales interactivo)
# ==========================================

ofertas_departamento_grafico = (
    jobs_clean['geographicDepartment']
    .fillna('SIN DEPARTAMENTO')
    .value_counts()
    .sort_values(ascending=True)
    .reset_index()
)

ofertas_departamento_grafico.columns = ['Departamento', 'Cantidad']

fig = px.bar(
    ofertas_departamento_grafico,
    x='Cantidad',
    y='Departamento',
    orientation='h',
    title='Distribución de ofertas laborales por departamento',
    labels={
        'Departamento': 'Departamento',
        'Cantidad': 'Número de ofertas'
    },
    text='Cantidad'
)

fig.update_traces(
    marker_color='#0a99ac',
    textposition='outside'
)

fig.update_layout(
    yaxis={'categoryorder': 'total ascending'}
)

fig.show()

Las ofertas laborales se concentran principalmente en Lima, con 434 registros, seguida de Arequipa, con 246, y La Libertad, con 214. Los demás departamentos presentan una cantidad considerablemente menor de oportunidades. Además, existen 36 ofertas sin departamento registrado, por lo que no pueden ser ubicadas geográficamente.

In [259]:
# ==========================================
# GRÁFICO 6: OFERTAS POR NIVEL DEL PUESTO
# (Gráfico de barras horizontales interactivo)
# ==========================================

ofertas_nivel_grafico = (
    jobs_clean['jobType']
    .fillna('SIN NIVEL')
    .value_counts()
    .sort_values(ascending=True)
    .reset_index()
)

ofertas_nivel_grafico.columns = ['Nivel', 'Cantidad']

fig = px.bar(
    ofertas_nivel_grafico,
    x='Cantidad',
    y='Nivel',
    orientation='h',
    title='Ofertas laborales por nivel del puesto',
    labels={
        'Nivel': 'Nivel del puesto',
        'Cantidad': 'Número de ofertas'
    },
    text='Cantidad'
)

fig.update_traces(
    marker_color='#0a99ac',
    textposition='outside'
)

fig.update_layout(
    yaxis={'categoryorder': 'total ascending'}
)

fig.show()

Entre las ofertas que cuentan con información sobre el nivel del puesto, predominan las oportunidades de tipo INTERNSHIP, con 413 registros, seguidas de PRACTICE, con 75, y JUNIOR, con 73. Esto evidencia una importante presencia de oportunidades orientadas a estudiantes y personas que buscan iniciar su experiencia profesional. Sin embargo, 472 ofertas no tienen registrado el nivel del puesto, por lo que deben considerarse al interpretar los resultados.

## CÓDIGO MODULAR

En esta etapa se organizará el código en funciones reutilizables. Esto permitirá evitar repetir el mismo código varias veces y
facilitará la ejecución de las métricas y gráficos. Se crearán funciones para tareas que se realizan de manera repetitiva, como contar valores, generar rankings y crear
gráficos. De esta forma, el código será más ordenado,fácil de entender, mantener y reutilizar.

Lo que estamos haciendo es ordenar el código para no escribir lo mismo muchas veces.
Por ejemplo, si tienes que hacer un gráfico para empresas, otro para departamentos y otro para niveles, en vez de escribir todo el código desde cero cada vez, creamos una función y la reutilizamos cambiando solamente los datos.

In [260]:
# ==========================================
# ASEGURAR CÓDIGO MODULAR
# 1. FUNCIÓN PARA CALCULAR TOTALES
# ==========================================

# Esta función permite calcular de forma reutilizable
# el total de registros únicos de una columna.
# De esta manera, podemos utilizarla para diferentes
# KPI sin repetir el mismo código.

def calcular_total_unico(df, columna):
    return df[columna].nunique()

In [261]:
# KPI 1: Total de empresas registradas

total_empresas = calcular_total_unico(
    companies_clean,
    '_id'
)

print(f"Total de empresas registradas en la plataforma: {total_empresas}")

Total de empresas registradas en la plataforma: 83


In [262]:
# KPI 3: Total de postulaciones registradas

total_postulaciones = calcular_total_unico(
    applications_clean,
    '_id'
)

print(f"Total de postulaciones registradas: {total_postulaciones}")

Total de postulaciones registradas: 467


In [263]:
# ==========================================
# ASEGURAR CÓDIGO MODULAR
# 2. FUNCIÓN PARA CONTAR CATEGORÍAS
# ==========================================

# Esta función permite obtener la cantidad de registros
# que corresponde a cada categoría de una columna.
# De esta manera, podemos reutilizar el mismo procedimiento
# para diferentes KPI sin repetir código.

def contar_categorias(df, columna, incluir_nulos=False):
    """
    Cuenta la cantidad de registros de cada categoría.
    """

    return df[columna].value_counts(
        dropna=not incluir_nulos
    )

In [264]:
# Prueba con las ofertas por modalidad

ofertas_modalidad_modular = contar_categorias(
    jobs_clean,
    'modality'
)

print(ofertas_modalidad_modular)

modality
presencial    952
híbrido        83
remoto         67
Name: count, dtype: int64


In [265]:
# ==========================================
# ASEGURAR CÓDIGO MODULAR
# 3. FUNCIÓN PARA GENERAR RANKINGS
# ==========================================

# Esta función permite obtener los valores con mayor
# frecuencia de una columna y generar un ranking.
# El parámetro top_n permite indicar cuántos resultados
# queremos mostrar.

def generar_ranking(df, columna, top_n=10):
    """
    Genera un ranking con los valores más frecuentes
    de una columna.
    """

    return (
        df[columna]
        .dropna()
        .value_counts()
        .head(top_n)
    )

In [266]:
# Prueba: ranking de empresas con mayor cantidad de ofertas

ranking_empresas_modular = generar_ranking(
    jobs_clean,
    'externalCompanyName',
    10
)

print(ranking_empresas_modular)

externalCompanyName
ManpowerGroup                      31
Importante Empresa en el sector    28
Caja Trujillo                      24
Caja Arequipa                      23
Bitel                              17
Adecco Perú S.A.                   14
Komatsu Mitsui                     12
Danper Trujillo SAC                12
Grupo Gloria                       10
Grupo Pacasmayo                     7
Name: count, dtype: int64


In [267]:
# KPI 2: Total de empleos registrados

total_empleos = calcular_total_unico(
    jobs_clean,
    '_id'
)

print(f"Total de empleos registrados: {total_empleos}")

Total de empleos registrados: 1102


In [268]:
# ==========================================
# FUNCIÓN: CONTAR REGISTROS SEGÚN CONDICIÓN
# ==========================================

def contar_condicion(df, columna, valor):
    """
    Cuenta la cantidad de registros que cumplen
    una condición determinada.
    """

    return df[columna].eq(valor).sum()

In [269]:
# KPI 5: Ofertas externas

ofertas_externas = contar_condicion(
    jobs_clean,
    'isExternalOffer',
    True
)

print(f"Total de ofertas externas: {ofertas_externas}")

Total de ofertas externas: 1044


In [270]:
# ==========================================
# FUNCIÓN: CONTEO DE REGISTROS POR MES
# ==========================================

def contar_por_mes(df, columna_fecha):
    """
    Cuenta la cantidad de registros agrupados
    por mes a partir de una columna de fecha.
    """

    return (
        df
        .assign(
            mes=df[columna_fecha].dt.to_period('M')
        )
        ['mes']
        .value_counts()
        .sort_index()
    )

In [271]:
# KPI 9: Ofertas publicadas por mes

ofertas_mes_modular = contar_por_mes(
    jobs_clean,
    'createdAt'
)

print(ofertas_mes_modular)

mes
2025-11      5
2025-12     12
2026-01     10
2026-02      9
2026-03      4
2026-04      6
2026-05      5
2026-06      9
2026-07    829
2026-08    213
Freq: M, Name: count, dtype: int64


In [272]:
# ==========================================
# ASEGURAR CÓDIGO MODULAR
# 2. FUNCIÓN PARA CONTAR CATEGORÍAS
# ==========================================

# Esta función permite contar los registros de cada
# categoría y, cuando sea necesario, identificar los
# valores nulos con una etiqueta como "SIN ESTADO".

def contar_categorias(df, columna, etiqueta_nulos=None):

    datos = df[columna].copy()

    if etiqueta_nulos is not None:
        datos = datos.fillna(etiqueta_nulos)

    return datos.value_counts()

In [273]:
# KPI 4: Postulaciones por estado

postulaciones_estado_modular = contar_categorias(
    applications_clean,
    'applicationStatus',
    'SIN ESTADO'
)

print(postulaciones_estado_modular)

applicationStatus
ENVIADO         209
SIN ESTADO      152
EN_REVISION      64
SELECCIONADO     25
DESCARTADO       12
RETIRADO          4
ENTREVISTA        1
Name: count, dtype: int64


In [274]:
ofertas_departamento_modular = contar_categorias(
    jobs_clean,
    'geographicDepartment'
)

print(ofertas_departamento_modular)

geographicDepartment
Lima           440
Arequipa       246
La Libertad    214
Ica             73
Callao          20
Piura           14
Lambayeque      11
Áncash          10
Cusco            9
Junín            9
Puno             7
Cajamarca        5
Apurímac         3
Ayacucho         2
Moquegua         2
Amazonas         1
Name: count, dtype: Int64


In [275]:
ofertas_nivel_modular = contar_categorias(
    jobs_clean,
    'jobType'
)

print(ofertas_nivel_modular)

jobType
INTERNSHIP    413
PRACTICE       81
JUNIOR         73
TRAINEE        40
SENIOR         23
Name: count, dtype: int64


In [276]:
# ==========================================
# ASEGURAR CÓDIGO MODULAR
# 5. FUNCIÓN PARA GRÁFICOS DE BARRAS
# ==========================================

# Esta función permite crear gráficos de barras
# reutilizando el mismo código para diferentes KPI.
# El color puede mantenerse como el color principal
# definido para el dashboard de Laboral.ai.

import plotly.express as px

def crear_grafico_barras(
    df,
    x,
    y,
    titulo,
    color='#0a99ac'
):

    fig = px.bar(
        df,
        x=x,
        y=y,
        title=titulo,
        text=y
    )

    fig.update_traces(
        marker_color=color,
        textposition='outside'
    )

    fig.update_layout(
        xaxis_title=x,
        yaxis_title=y,
        hovermode='x unified'
    )

    fig.show()

In [277]:
# Preparar datos para el gráfico de postulaciones

postulaciones_grafico_modular = (
    applications_clean['applicationStatus']
    .fillna('SIN ESTADO')
    .value_counts()
    .reset_index()
)

postulaciones_grafico_modular.columns = [
    'Estado',
    'Cantidad'
]

In [278]:
crear_grafico_barras(
    postulaciones_grafico_modular,
    'Estado',
    'Cantidad',
    'Postulaciones por estado'
)


## VINCULAR ESPACIO DE TRABAJO A GITHUB

In [279]:
print("Laboral AI - Análisis de KPIs")

Laboral AI - Análisis de KPIs


In [280]:
# Variables disponibles en el notebook
variables = [x for x in globals() if not x.startswith("_")]

print("Variables disponibles:")
print(variables)

Variables disponibles:
['In', 'Out', 'get_ipython', 'exit', 'quit', 'MongoClient', 'np', 'pd', 'MONGO_URI', 'DB_NAME', 'SAMPLE_SIZE', 'conectar_mongo', 'obtener_colecciones', 'muestrear_coleccion', 'analizar_dataframe', 'analizar_colecciones', 'db', 'resumen', 'coleccion', 'tabla', 'client', 'colecciones', 'c', 'inventario', 'cantidad', 'df', 'company', 'campo', 'valor', 'df_companies', 'perfil', 'col', 'unicos', 'df_jobs', 'perfil_jobs', 'df_applications', 'perfil_applications', 'df_payments', 'perfil_payments', 'df_users', 'perfil_users', 'df_candidate_profiles', 'perfil_candidate_profiles', 'companies', 'jobs', 'applications', 'companies_clean', 'columnas_texto', 'jobs_clean', 'columnas_texto_jobs', 'valores_invalidos', 'correcciones_department', 'applications_clean', 'status_grafico', 'company_ids', 'job_company_ids', 'coincidencias', 'job_ids', 'application_job_ids', 'coincidencias_jobs', 'applications_jobs', 'job_ejemplo', 'jobs_ids', 'coincidentes', 'coincidencias_companies', 'a

In [281]:
applications_final

,_id_application,job,createdAt_application,applicationStatus,_id_job,companyId,title,department,modality,publishUntil,...,externalCompanyName,_id,businessName,industry,verificationStatus_company,country_company,plan,isActive,createdAt,planType
0,6917cdf4998d66b34dac075b,6917cd88998d66b34dac0734,2025-11-15 00:48:52.932,NaN,NaN,NaN,NaN,NaN,NaN,NaT,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN
1,692867743b4884927933f66e,692797626dc39bf20c52f60f,2025-11-27 15:00:04.307,NaN,NaN,NaN,NaN,NaN,NaN,NaT,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN
2,6928ab6e985136edda36ae82,69279ce46dc39bf20c52f61c,2025-11-27 19:50:06.623,NaN,NaN,NaN,NaN,NaN,NaN,NaT,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN
3,692a2b217f1f3ab5036abc0d,69279ddf6dc39bf20c52f62f,2025-11-28 23:07:13.054,NaN,NaN,NaN,NaN,NaN,NaN,NaT,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN
4,692a5c537f1f3ab5036abe21,69279ce46dc39bf20c52f61c,2025-11-29 02:37:07.991,NaN,NaN,NaN,NaN,NaN,NaN,NaT,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
462,6a517a68269dd13c50d6daad,6a322db504845a0f4ea75f42,2026-07-10 23:04:08.873,ENVIADO,NaN,NaN,NaN,NaN,NaN,NaT,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN
463,6a517ab6269dd13c50d6dad3,6a322db504845a0f4ea75f42,2026-07-10 23:05:26.989,ENVIADO,NaN,NaN,NaN,NaN,NaN,NaT,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN
464,6a517b64269dd13c50d6db03,6a322db504845a0f4ea75f42,2026-07-10 23:08:20.857,ENVIADO,NaN,NaN,NaN,NaN,NaN,NaT,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN
465,6a517be2269dd13c50d6db2f,6a322db504845a0f4ea75f42,2026-07-10 23:10:26.647,ENVIADO,NaN,NaN,NaN,NaN,NaN,NaT,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN


In [282]:
print("Dimensiones del dataset final:")
print("Filas:", applications_final.shape[0])
print("Columnas:", applications_final.shape[1])

print("\nColumnas:")
print(applications_final.columns.tolist())

Dimensiones del dataset final:
Filas: 467
Columnas: 27

Columnas:
['_id_application', 'job', 'createdAt_application', 'applicationStatus', '_id_job', 'companyId', 'title', 'department', 'modality', 'publishUntil', 'status', 'createdAt_job', 'country', 'geographicDepartment', 'jobType', 'verificationStatus', 'isExternalOffer', 'externalCompanyName', '_id', 'businessName', 'industry', 'verificationStatus_company', 'country_company', 'plan', 'isActive', 'createdAt', 'planType']


In [283]:
display(applications_final.head())

,_id_application,job,createdAt_application,applicationStatus,_id_job,companyId,title,department,modality,publishUntil,...,externalCompanyName,_id,businessName,industry,verificationStatus_company,country_company,plan,isActive,createdAt,planType
0,6917cdf4998d66b34dac075b,6917cd88998d66b34dac0734,2025-11-15 00:48:52.932,NaN,NaN,NaN,NaN,NaN,NaN,NaT,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN
1,692867743b4884927933f66e,692797626dc39bf20c52f60f,2025-11-27 15:00:04.307,NaN,NaN,NaN,NaN,NaN,NaN,NaT,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN
2,6928ab6e985136edda36ae82,69279ce46dc39bf20c52f61c,2025-11-27 19:50:06.623,NaN,NaN,NaN,NaN,NaN,NaN,NaT,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN
3,692a2b217f1f3ab5036abc0d,69279ddf6dc39bf20c52f62f,2025-11-28 23:07:13.054,NaN,NaN,NaN,NaN,NaN,NaN,NaT,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN
4,692a5c537f1f3ab5036abe21,69279ce46dc39bf20c52f61c,2025-11-29 02:37:07.991,NaN,NaN,NaN,NaN,NaN,NaN,NaT,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN
